-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 11 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Availability check uses or instead of and$$,
    $$javascript$$,
    $$logic_error$$,
    $$hard$$,
    $$isAvailable$$,
    $$function isAvailable(item) {
    return item.inStock || !item.discontinued;
}$$,
    $$function isAvailable(item) {
    return item.inStock && !item.discontinued;
}$$,
    $$isAvailable(item) should be true only when the item is in stock AND not discontinued.$$,
    $$isAvailable({inStock: false, discontinued: false}) returns true — an out-of-stock item is offered for sale.$$,
    $$With ||, either condition alone is enough, so an item that is merely 'not discontinued' passes even with nothing in stock. Requirements phrased with 'and' need &&; 'or' is strictly weaker and will let extra cases through. These read almost identically, and the bug only shows up for inputs where the two conditions disagree — which is precisely the combination that a happy-path test never covers. Build a small truth table when a boolean expression has more than one term.$$,
    $$[{"input":[{"inStock":false,"discontinued":false}],"expected_output":false},{"input":[{"inStock":true,"discontinued":false}],"expected_output":true},{"input":[{"inStock":true,"discontinued":true}],"expected_output":false}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try an item that is out of stock but not discontinued. What should happen?$$ from new_challenge
union all
select id, 2, $$The requirement says AND. What does the code say?$$ from new_challenge
union all
select id, 3, $$|| passes if either side is true. Use && so both must hold.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Percentage change comes out backwards$$,
    $$javascript$$,
    $$logic_error$$,
    $$medium$$,
    $$percentChange$$,
    $$function percentChange(oldValue, newValue) {
    return ((oldValue - newValue) / oldValue) * 100;
}$$,
    $$function percentChange(oldValue, newValue) {
    return ((newValue - oldValue) / oldValue) * 100;
}$$,
    $$percentChange(oldValue, newValue) should report the change as a percentage of the old value. Going from 100 to 150 is +50.$$,
    $$percentChange(100, 150) returns -50 instead of 50 — a rise is reported as a fall.$$,
    $$The subtraction is the wrong way round. Change is always new minus old, so growth is positive and a drop is negative; reversing it flips the sign of every result. The magnitude is right, which is what makes it easy to miss — the numbers look plausible on a dashboard until someone notices growth being drawn downwards. Whenever a formula produces a signed result, test one case in each direction.$$,
    $$[{"input":[100,150],"expected_output":50},{"input":[100,50],"expected_output":-50},{"input":[200,200],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The size of the answer is right but something else is not.$$ from new_challenge
union all
select id, 2, $$Should an increase come out positive or negative?$$ from new_challenge
union all
select id, 3, $$Change is new - old, not old - new.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$any where all was meant$$,
    $$python$$,
    $$logic_error$$,
    $$medium$$,
    $$all_positive$$,
    $$def all_positive(nums):
    return any(n > 0 for n in nums)$$,
    $$def all_positive(nums):
    return all(n > 0 for n in nums)$$,
    $$all_positive(nums) should return True only when EVERY number is greater than zero.$$,
    $$all_positive([1, -2]) returns True even though -2 is not positive.$$,
    $$any() is True when at least one item passes; all() requires every item to pass. Swapping them gives an answer that is right whenever the list is entirely positive or entirely negative, and wrong for every mixed list — so casual testing tends to confirm it. One more difference worth knowing: on an empty list any() is False but all() is True, which is the mathematically standard 'vacuous truth' and occasionally surprising in its own right.$$,
    $$[{"input":[[1,-2]],"expected_output":false},{"input":[[1,2,3]],"expected_output":true},{"input":[[-1,-2]],"expected_output":false}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try a list with one positive and one negative number.$$ from new_challenge
union all
select id, 2, $$Does the code require every item to pass, or just one?$$ from new_challenge
union all
select id, 3, $$any() needs only one match. Use all().$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Guard checked after the division it protects$$,
    $$python$$,
    $$logic_error$$,
    $$hard$$,
    $$safe_ratio$$,
    $$def safe_ratio(a, b):
    if a / b > 1 and b != 0:
        return True
    return False$$,
    $$def safe_ratio(a, b):
    if b != 0 and a / b > 1:
        return True
    return False$$,
    $$safe_ratio(a, b) should return True when a / b is greater than 1, and False when b is zero rather than crashing.$$,
    $$safe_ratio(1, 0) raises ZeroDivisionError instead of returning False, even though the code checks b != 0.$$,
    $$`and` evaluates left to right and short-circuits, so the guard has to come FIRST to be of any use. Written the other way round, the division has already happened by the time b != 0 is considered. The check is present but powerless — which is worse than no check at all, because it makes the code look safe under review. The rule: a guard must appear before whatever it guards, in evaluation order rather than in reading order.$$,
    $$[{"input":[4,2],"expected_output":true},{"input":[1,0],"expected_output":false},{"input":[1,4],"expected_output":false}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The zero check exists. Has it run yet at the point of the crash?$$ from new_challenge
union all
select id, 2, $$In what order does Python evaluate the two sides of `and`?$$ from new_challenge
union all
select id, 3, $$Short-circuiting only helps if the guard is on the left: b != 0 and a / b > 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Gaps between readings come out negative$$,
    $$python$$,
    $$logic_error$$,
    $$medium$$,
    $$largest_gap$$,
    $$def largest_gap(nums):
    gaps = []
    for i in range(len(nums) - 1):
        gaps.append(nums[i] - nums[i + 1])
    return max(gaps)$$,
    $$def largest_gap(nums):
    gaps = []
    for i in range(len(nums) - 1):
        gaps.append(nums[i + 1] - nums[i])
    return max(gaps)$$,
    $$largest_gap(nums) should return the biggest jump between consecutive values in an ascending list, so largest_gap([1, 5, 6]) returns 4.$$,
    $$largest_gap([1, 5, 6]) returns -1 instead of 4 — every gap is negative.$$,
    $$The subtraction is reversed: for an ascending list, nums[i] - nums[i+1] is always negative, so max() ends up picking the SMALLEST real gap (the one closest to zero). Two errors stack here — the sign flip and the resulting inversion of what max means — which is why the answer looks unrelated to the input rather than merely negated. Reversing a subtraction is easy to do and easy to spot once you check a single pair by hand.$$,
    $$[{"input":[[1,5,6]],"expected_output":4},{"input":[[0,1,2]],"expected_output":1},{"input":[[2,10]],"expected_output":8}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Work out the first gap by hand and compare it with what the code computes.$$ from new_challenge
union all
select id, 2, $$For an ascending list, which of the two values is larger?$$ from new_challenge
union all
select id, 3, $$The subtraction is backwards: use nums[i + 1] - nums[i].$$ from new_challenge;
