-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Second batch, part 1 of 5 (6 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Last N characters comes back one too long$$,
    $$python$$,
    $$off_by_one$$,
    $$medium$$,
    $$last_n_chars$$,
    $$def last_n_chars(text, n):
    return text[len(text) - n - 1:]$$,
    $$def last_n_chars(text, n):
    return text[len(text) - n:]$$,
    $$last_n_chars(text, n) should return the last n characters of a string, so last_n_chars("debugging", 3) gives "ing".$$,
    $$last_n_chars("debugging", 3) returns "ging" — four characters instead of three.$$,
    $$The slice starts one index too early. The last n characters begin at index len(text) - n; subtracting an extra 1 reaches back one character further. Whenever you compute an index from a length, check it against a tiny example by hand — here, a 9-character string wanting the last 3 should start at index 6, not 5.$$,
    $$[{"input":["debugging",3],"expected_output":"ing"},{"input":["hello",2],"expected_output":"lo"},{"input":["abc",3],"expected_output":"abc"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Count the characters in the result by hand — how many did you get versus how many you asked for?$$ from new_challenge
union all
select id, 2, $$The starting index of the slice is the problem.$$ from new_challenge
union all
select id, 3, $$The last n characters start at len(text) - n. Drop the extra - 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$First chunk drops its last item$$,
    $$javascript$$,
    $$off_by_one$$,
    $$easy$$,
    $$firstChunk$$,
    $$function firstChunk(arr, size) {
    return arr.slice(0, size - 1);
}$$,
    $$function firstChunk(arr, size) {
    return arr.slice(0, size);
}$$,
    $$firstChunk(arr, size) should return the first `size` items of an array, so firstChunk([1,2,3,4,5], 3) gives [1,2,3].$$,
    $$firstChunk([1,2,3,4,5], 3) returns [1,2] — one item short.$$,
    $$slice's second argument is the index to stop *before*, not the last index to include. slice(0, size) already returns exactly `size` items, so subtracting 1 removes one too many. This is the mirror image of the more common mistake of forgetting that the end index is exclusive.$$,
    $$[{"input":[[1,2,3,4,5],3],"expected_output":[1,2,3]},{"input":[[1,2],2],"expected_output":[1,2]},{"input":[[1,2,3],1],"expected_output":[1]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Count the items you get back versus the number you asked for.$$ from new_challenge
union all
select id, 2, $$Look at the second argument to slice().$$ from new_challenge
union all
select id, 3, $$slice(0, size) already returns exactly size items — the - 1 is removing one too many.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Binary search misses the last element$$,
    $$python$$,
    $$off_by_one$$,
    $$hard$$,
    $$binary_search$$,
    $$def binary_search(nums, target):
    low = 0
    high = len(nums) - 1
    while low < high:
        mid = (low + high) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1$$,
    $$def binary_search(nums, target):
    low = 0
    high = len(nums) - 1
    while low <= high:
        mid = (low + high) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1$$,
    $$binary_search(nums, target) should return the index of target in a sorted list, or -1 if it isn't there.$$,
    $$It works for most values but returns -1 for some that are definitely present — searching for 9 in [1,3,5,7,9] gives -1.$$,
    $$The loop condition `low < high` exits when low and high meet, so the single remaining candidate is never checked. Binary search must keep going while the search window still contains one element, which means `low <= high`. Bugs like this hide well because they only show up when the target lands on the final narrowing step.$$,
    $$[{"input":[[1,3,5,7,9],9],"expected_output":4},{"input":[[1,3,5,7,9],1],"expected_output":0},{"input":[[1,3,5,7,9],5],"expected_output":2},{"input":[[1,3,5],4],"expected_output":-1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It only fails for certain targets. What do those targets have in common?$$ from new_challenge
union all
select id, 2, $$Think about the moment when low and high become equal — does the loop still run?$$ from new_challenge
union all
select id, 3, $$When low == high there is still one unchecked element. The condition should be low <= high.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$First item's name crashes on an empty list$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$easy$$,
    $$firstItemName$$,
    $$function firstItemName(items) {
    return items[0].name;
}$$,
    $$function firstItemName(items) {
    return items.length > 0 ? items[0].name : "None";
}$$,
    $$firstItemName(items) should return the name of the first item, or "None" when the list is empty.$$,
    $$Passing an empty array throws "Cannot read properties of undefined (reading 'name')".$$,
    $$Indexing past the end of an array gives undefined rather than throwing, so the error surfaces one step later when .name is read from it. Guard on the array being non-empty before reaching into it. The lesson generalises: in JavaScript an out-of-range index fails silently, and you find out at the next property access.$$,
    $$[{"input":[[{"name":"first"},{"name":"second"}]],"expected_output":"first"},{"input":[[]],"expected_output":"None"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What does items[0] evaluate to when the array has nothing in it?$$ from new_challenge
union all
select id, 2, $$The return line assumes there is always a first item.$$ from new_challenge
union all
select id, 3, $$Check items.length before reading items[0].name, and return "None" otherwise.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Optional middle name breaks the full name$$,
    $$python$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$full_name$$,
    $$def full_name(user):
    return user["first"] + " " + user["middle"] + " " + user["last"]$$,
    $$def full_name(user):
    parts = [user["first"], user.get("middle"), user["last"]]
    return " ".join(p for p in parts if p)$$,
    $$full_name(user) should join a user's name parts with single spaces, skipping the middle name when there isn't one.$$,
    $$A user without a "middle" key crashes with KeyError, and one whose middle name is None crashes with a TypeError.$$,
    $$The code assumes every optional field is both present and a string. Two separate failure modes hide here: a missing key raises KeyError, and a present-but-None value fails to concatenate. Collecting the parts and filtering out the falsy ones handles both at once, and keeps the spacing correct instead of leaving a double space.$$,
    $$[{"input":[{"first":"Ada","middle":"Byron","last":"Lovelace"}],"expected_output":"Ada Byron Lovelace"},{"input":[{"first":"Alan","last":"Turing"}],"expected_output":"Alan Turing"},{"input":[{"first":"Grace","middle":null,"last":"Hopper"}],"expected_output":"Grace Hopper"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$There are two different ways this breaks — try a user with no middle key, then one whose middle is None.$$ from new_challenge
union all
select id, 2, $$Both failures come from the same line assuming every part exists and is a string.$$ from new_challenge
union all
select id, 3, $$Gather the parts into a list, drop the empty ones, and " ".join() what remains.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Total score comes out as NaN$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$sumScores$$,
    $$function sumScores(players) {
    let total = 0;
    for (const player of players) {
        total += player.score;
    }
    return total;
}$$,
    $$function sumScores(players) {
    let total = 0;
    for (const player of players) {
        total += player.score ?? 0;
    }
    return total;
}$$,
    $$sumScores(players) should add up every player's score, treating a player with no score as 0.$$,
    $$As soon as one player is missing a score, the total becomes NaN instead of a number.$$,
    $$Reading a missing property gives undefined, and undefined + number is NaN. Worse, NaN is contagious: once it enters the running total every later addition stays NaN, so one bad record poisons the whole result. Default the value at the point you read it.$$,
    $$[{"input":[[{"score":10},{"score":20}]],"expected_output":30},{"input":[[{"score":10},{},{"score":5}]],"expected_output":15},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What is the value of player.score for a player object with no score property?$$ from new_challenge
union all
select id, 2, $$Once the total becomes NaN it never recovers — look at what is being added.$$ from new_challenge
union all
select id, 3, $$Use player.score ?? 0 so a missing score contributes zero instead of undefined.$$ from new_challenge;
