-- Generated by scripts/generate-seed-sql.mjs from lib/seed-data/phase3-challenges.mjs
-- Do not hand-edit — change the source data and regenerate instead.
-- Run in the Supabase SQL Editor after 0001_init.sql and 0002_add_function_name.sql.
-- Only inserts challenges that weren't already seeded in Phase 1.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Countdown that never ends$$,
    $$python$$,
    $$infinite_loop$$,
    $$medium$$,
    $$countdown$$,
    $$def countdown(n):
    result = []
    while n > 0:
        result.append(n)
    return result$$,
    $$def countdown(n):
    result = []
    while n > 0:
        result.append(n)
        n -= 1
    return result$$,
    $$countdown(n) should return a list counting down from n to 1, e.g. countdown(3) -> [3, 2, 1].$$,
    $$Calling countdown(3) freezes and never returns.$$,
    $$The loop condition (n > 0) never changes because n is never decremented inside the loop, so it runs forever. Every loop needs its condition to eventually become false — always double-check that whatever the condition depends on actually changes each iteration.$$,
    $$[{"input":[3],"expected_output":[3,2,1]},{"input":[1],"expected_output":[1]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The loop condition depends on n — does anything inside the loop ever change n?$$ from new_challenge
union all
select id, 2, $$Look at the while loop body — something is missing after result.append(n).$$ from new_challenge
union all
select id, 3, $$Add n -= 1 inside the loop so n eventually reaches 0 and the condition becomes false.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$isEven that returns the opposite$$,
    $$javascript$$,
    $$logic_error$$,
    $$easy$$,
    $$isEven$$,
    $$function isEven(n) {
    return n % 2 === 1;
}$$,
    $$function isEven(n) {
    return n % 2 === 0;
}$$,
    $$isEven(n) should return true if n is even, false otherwise.$$,
    $$isEven(4) returns false and isEven(3) returns true — the results are backwards.$$,
    $$n % 2 === 1 is the condition for odd, not even. A number is even when the remainder after dividing by 2 is 0, so the comparison should be === 0. Small logic inversions like this are easy to introduce and easy to miss without testing both true and false cases.$$,
    $$[{"input":[4],"expected_output":true},{"input":[3],"expected_output":false},{"input":[0],"expected_output":true}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Test isEven with both an even and an odd number by hand — which one comes out wrong?$$ from new_challenge
union all
select id, 2, $$The comparison operator on the return line is checking for the wrong remainder.$$ from new_challenge
union all
select id, 3, $$n % 2 === 0 is true for even numbers; n % 2 === 1 is true for odd numbers. This function needs the first one.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Price formatting crashes on numbers$$,
    $$python$$,
    $$type_error$$,
    $$easy$$,
    $$format_price$$,
    $$def format_price(amount):
    return "$" + amount$$,
    $$def format_price(amount):
    return "$" + str(amount)$$,
    $$format_price(amount) should return the amount formatted as a price string, e.g. format_price(5) -> "$5".$$,
    $$Calling format_price(5) crashes with: TypeError: can only concatenate str (not "int") to str.$$,
    $$Python won't implicitly convert a number to a string when using +. amount needs to be explicitly converted with str(amount) before it can be concatenated onto "$". This is a very common type error at the boundary between numbers and display strings.$$,
    $$[{"input":[5],"expected_output":"$5"},{"input":[9.99],"expected_output":"$9.99"},{"input":[0],"expected_output":"$0"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What types are being combined with the + operator here?$$ from new_challenge
union all
select id, 2, $$The return line tries to add a string and a number directly.$$ from new_challenge
union all
select id, 3, $$Wrap amount in str() before concatenating: "$" + str(amount).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Result variable that vanishes after the loop$$,
    $$javascript$$,
    $$scope_error$$,
    $$medium$$,
    $$findFirstNegative$$,
    $$function findFirstNegative(nums) {
    for (let i = 0; i < nums.length; i++) {
        if (nums[i] < 0) {
            let result = nums[i];
        }
    }
    return result;
}$$,
    $$function findFirstNegative(nums) {
    let result = null;
    for (let i = 0; i < nums.length; i++) {
        if (nums[i] < 0) {
            result = nums[i];
            break;
        }
    }
    return result;
}$$,
    $$findFirstNegative(nums) should return the first negative number in the array, or null if there isn't one.$$,
    $$Calling findFirstNegative with any array throws: ReferenceError: result is not defined.$$,
    $$result is declared with let inside the if block, so it only exists within that block — it's completely inaccessible once execution reaches the return statement outside the loop. Declare result once, outside the loop, so it's in scope for the whole function.$$,
    $$[{"input":[[3,-2,5]],"expected_output":-2},{"input":[[1,2,3]],"expected_output":null},{"input":[[-5,-2,3]],"expected_output":-5}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Where is result declared, and where is it being used? Are those the same scope?$$ from new_challenge
union all
select id, 2, $$let and const are block-scoped — look at exactly which block result is declared inside.$$ from new_challenge
union all
select id, 3, $$Move `let result = null;` to before the loop so it's visible both inside the loop and at the return statement.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Doubled value returned before it's ready$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$delayedDouble$$,
    $$function delayedDouble(n) {
    let result;
    new Promise((resolve) => setTimeout(() => resolve(n * 2), 10)).then((r) => {
        result = r;
    });
    return result;
}$$,
    $$function delayedDouble(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n * 2), 10)).then((r) => r);
}$$,
    $$delayedDouble(n) should asynchronously resolve to n doubled, e.g. delayedDouble(5) eventually resolves to 10.$$,
    $$Awaiting delayedDouble(5) gives undefined instead of 10.$$,
    $$The function returns result immediately, before the Promise's setTimeout callback ever runs — result is still undefined at that point. The function needs to return the Promise itself (or the chained .then()) so callers can await the value once it's actually ready, instead of racing ahead of it.$$,
    $$[{"input":[5],"expected_output":10},{"input":[3],"expected_output":6},{"input":[0],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$When does the code inside setTimeout actually run, compared to when the function returns?$$ from new_challenge
union all
select id, 2, $$The function returns result on the line right after starting the Promise — is that too early?$$ from new_challenge
union all
select id, 3, $$Return the Promise chain itself (return new Promise(...).then(...)) instead of a variable that the async callback hasn't filled in yet.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Factorial that never stops recursing$$,
    $$python$$,
    $$other$$,
    $$medium$$,
    $$factorial$$,
    $$def factorial(n):
    return n * factorial(n - 1)$$,
    $$def factorial(n):
    if n <= 1:
        return 1
    return n * factorial(n - 1)$$,
    $$factorial(n) should return n! (n factorial), e.g. factorial(5) -> 120.$$,
    $$Calling factorial(5) crashes with a RecursionError about exceeding the maximum recursion depth.$$,
    $$The function has no base case, so it keeps calling itself with smaller and smaller n forever (n, n-1, n-2, ... with no stopping point) until Python's recursion limit is hit. Every recursive function needs a base case that returns a value directly instead of recursing again.$$,
    $$[{"input":[5],"expected_output":120},{"input":[0],"expected_output":1},{"input":[1],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What stops this function from calling itself? Is there any condition that returns without recursing?$$ from new_challenge
union all
select id, 2, $$Recursive functions need a base case — this one is missing entirely.$$ from new_challenge
union all
select id, 3, $$Add `if n <= 1: return 1` before the recursive call, so the recursion has somewhere to stop.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Off-by-one when slicing the last N items$$,
    $$javascript$$,
    $$off_by_one$$,
    $$medium$$,
    $$getLastNItems$$,
    $$function getLastNItems(arr, n) {
    return arr.slice(arr.length - n - 1);
}$$,
    $$function getLastNItems(arr, n) {
    return arr.slice(arr.length - n);
}$$,
    $$getLastNItems(arr, n) should return the last n items of arr, e.g. getLastNItems([1,2,3,4,5], 2) -> [4, 5].$$,
    $$getLastNItems([1,2,3,4,5], 2) returns [3, 4, 5] — one extra item at the front.$$,
    $$arr.length - n - 1 starts the slice one index too early, pulling in an extra element. The correct starting index for "the last n items" is exactly arr.length - n, with no extra -1.$$,
    $$[{"input":[[1,2,3,4,5],2],"expected_output":[4,5]},{"input":[[1,2,3],1],"expected_output":[3]},{"input":[[1,2,3,4],0],"expected_output":[]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Work out arr.length - n - 1 by hand for a small example — does the slice start where you'd expect?$$ from new_challenge
union all
select id, 2, $$The extra -1 in the slice's starting index is the problem.$$ from new_challenge
union all
select id, 3, $$The last n items of an array start at index arr.length - n — drop the extra - 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Checkout allowed without valid payment$$,
    $$python$$,
    $$logic_error$$,
    $$easy$$,
    $$can_checkout$$,
    $$def can_checkout(cart_total, has_valid_payment):
    return cart_total > 0 or has_valid_payment$$,
    $$def can_checkout(cart_total, has_valid_payment):
    return cart_total > 0 and has_valid_payment$$,
    $$can_checkout(cart_total, has_valid_payment) should return True only when the cart has items AND payment is valid.$$,
    $$can_checkout(50, False) returns True — checkout is allowed even without valid payment.$$,
    $$or lets either condition alone make the result True, so a full cart with no valid payment (or an empty cart with valid payment) both incorrectly pass. Checkout should require both conditions to hold at once, which is what and does.$$,
    $$[{"input":[50,false],"expected_output":false},{"input":[0,true],"expected_output":false},{"input":[50,true],"expected_output":true}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try a cart with items but no valid payment — should checkout succeed? What does the function actually do?$$ from new_challenge
union all
select id, 2, $$The boolean operator joining the two conditions is the issue.$$ from new_challenge
union all
select id, 3, $$Both conditions need to be true at once for checkout to succeed — use `and` instead of `or`.$$ from new_challenge;
