-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Fourth batch, part 1 of 1 (4 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$The list that remembers$$,
    $$python$$,
    $$scope_error$$,
    $$medium$$,
    $$test_append$$,
    $$def append_to_list(val, lst=[]):
    lst.append(val)
    return lst

def test_append():
    return [append_to_list(1), append_to_list(2)]$$,
    $$def append_to_list(val, lst=None):
    if lst is None:
        lst = []
    lst.append(val)
    return lst

def test_append():
    return [append_to_list(1), append_to_list(2)]$$,
    $$append_to_list(val) should create a new list with val if no list is provided. test_append() calls it twice with 1 and 2.$$,
    $$test_append() returns [[1, 2], [1, 2]] because both calls share the same list in memory.$$,
    $$Default arguments in Python are evaluated exactly ONCE when the function is defined, not each time it is called. Because a list is mutable, every call that omits the argument uses the exact same list in memory. The standard fix is to use None as the default and create a fresh list inside the function.$$,
    $$[{"input":[],"expected_output":[[1],[2]]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try calling it twice in a row in your head. What happens to 'lst'?$$ from new_challenge
union all
select id, 2, $$Default arguments are created when the function is defined, not when it runs.$$ from new_challenge
union all
select id, 3, $$Use lst=None as the default, and set lst = [] inside the function if it is None.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$The loop variable that changed$$,
    $$python$$,
    $$scope_error$$,
    $$hard$$,
    $$test_multipliers$$,
    $$def make_multipliers():
    return [lambda x: i * x for i in range(3)]

def test_multipliers():
    return [f(10) for f in make_multipliers()]$$,
    $$def make_multipliers():
    return [lambda x, i=i: i * x for i in range(3)]

def test_multipliers():
    return [f(10) for f in make_multipliers()]$$,
    $$make_multipliers() returns a list of 3 functions multiplying by 0, 1, and 2. test_multipliers() calls each with 10 and returns the results.$$,
    $$test_multipliers() returns [20, 20, 20] instead of [0, 10, 20].$$,
    $$Python closures are late-binding. The lambda function looks up the value of 'i' in the surrounding scope at the time it is CALLED, not when it is created. By the time you call them, the loop has finished and 'i' is 2. The standard fix is to bind 'i' as a default argument (i=i), which forces it to be evaluated immediately.$$,
    $$[{"input":[],"expected_output":[0,10,20]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$When does the lambda look up the value of 'i' — when it's created, or when it's called?$$ from new_challenge
union all
select id, 2, $$By the time the functions are called, what is the final value of the loop variable?$$ from new_challenge
union all
select id, 3, $$Bind 'i' as a default argument to freeze its value: lambda x, i=i: i * x.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Sorting numbers alphabetically$$,
    $$javascript$$,
    $$logic_error$$,
    $$easy$$,
    $$sortNumbers$$,
    $$function sortNumbers(arr) {
    return arr.sort();
}$$,
    $$function sortNumbers(arr) {
    return arr.sort((a, b) => a - b);
}$$,
    $$sortNumbers(arr) should sort an array of numbers from smallest to largest.$$,
    $$sortNumbers([10, 2, 30]) returns [10, 2, 30] instead of [2, 10, 30].$$,
    $$In JavaScript, Array.prototype.sort() converts elements to strings and compares their UTF-16 code units by default. Alphabetically, '10' comes before '2'. To sort numbers numerically, you must provide a comparison function that subtracts one from the other.$$,
    $$[{"input":[[10,2,30]],"expected_output":[2,10,30]},{"input":[[5,1,100]],"expected_output":[1,5,100]},{"input":[[-1,-10,0]],"expected_output":[-10,-1,0]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Why would 10 come before 2? What data type sorts like that?$$ from new_challenge
union all
select id, 2, $$JavaScript's default sort converts everything to strings first.$$ from new_challenge
union all
select id, 3, $$Pass a comparator function: arr.sort((a, b) => a - b).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Mapping strings to numbers$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$parseAll$$,
    $$function parseAll(strings) {
    return strings.map(parseInt);
}$$,
    $$function parseAll(strings) {
    return strings.map(str => parseInt(str, 10));
}$$,
    $$parseAll(strings) should take an array of numeric strings and return an array of integers.$$,
    $$parseAll(["10", "10", "10"]) returns [10, NaN, 2].$$,
    $$Array.prototype.map passes THREE arguments to the callback: the element, its index, and the array. parseInt takes TWO arguments: the string, and the radix (base). So map calls parseInt('10', 0), parseInt('10', 1), and parseInt('10', 2). Base 0 defaults to 10, base 1 is invalid (NaN), and base 2 parses '10' as 2.$$,
    $$[{"input":[["10","10","10"]],"expected_output":[10,10,10]},{"input":[["11","12","13"]],"expected_output":[11,12,13]},{"input":[["1"]],"expected_output":[1]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$map() passes more than just the array element to its callback.$$ from new_challenge
union all
select id, 2, $$parseInt() takes a second argument (the radix). What is map() passing as the second argument?$$ from new_challenge
union all
select id, 3, $$map() passes the index. Wrap it in a function: str => parseInt(str, 10).$$ from new_challenge;
