-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Second batch: 30 challenges, four per bug category.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Last N characters comes back one too long$$,
    $$python$$,
    $$off_by_one$$,
    $$medium$$,
    $$last_n_chars$$,
    $$def last_n_chars(text, n):
    return text[len(text) - n - 1:]$$,
    $$def last_n_chars(text, n):
    return text[len(text) - n:]$$,
    $$last_n_chars(text, n) should return the last n characters of a string, so last_n_chars("debugging", 3) gives "ing".$$,
    $$last_n_chars("debugging", 3) returns "ging" — four characters instead of three.$$,
    $$The slice starts one index too early. The last n characters begin at index len(text) - n; subtracting an extra 1 reaches back one character further. Whenever you compute an index from a length, check it against a tiny example by hand — here, a 9-character string wanting the last 3 should start at index 6, not 5.$$,
    $$[{"input":["debugging",3],"expected_output":"ing"},{"input":["hello",2],"expected_output":"lo"},{"input":["abc",3],"expected_output":"abc"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Count the characters in the result by hand — how many did you get versus how many you asked for?$$ from new_challenge
union all
select id, 2, $$The starting index of the slice is the problem.$$ from new_challenge
union all
select id, 3, $$The last n characters start at len(text) - n. Drop the extra - 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$First chunk drops its last item$$,
    $$javascript$$,
    $$off_by_one$$,
    $$easy$$,
    $$firstChunk$$,
    $$function firstChunk(arr, size) {
    return arr.slice(0, size - 1);
}$$,
    $$function firstChunk(arr, size) {
    return arr.slice(0, size);
}$$,
    $$firstChunk(arr, size) should return the first `size` items of an array, so firstChunk([1,2,3,4,5], 3) gives [1,2,3].$$,
    $$firstChunk([1,2,3,4,5], 3) returns [1,2] — one item short.$$,
    $$slice's second argument is the index to stop *before*, not the last index to include. slice(0, size) already returns exactly `size` items, so subtracting 1 removes one too many. This is the mirror image of the more common mistake of forgetting that the end index is exclusive.$$,
    $$[{"input":[[1,2,3,4,5],3],"expected_output":[1,2,3]},{"input":[[1,2],2],"expected_output":[1,2]},{"input":[[1,2,3],1],"expected_output":[1]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Count the items you get back versus the number you asked for.$$ from new_challenge
union all
select id, 2, $$Look at the second argument to slice().$$ from new_challenge
union all
select id, 3, $$slice(0, size) already returns exactly size items — the - 1 is removing one too many.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Binary search misses the last element$$,
    $$python$$,
    $$off_by_one$$,
    $$hard$$,
    $$binary_search$$,
    $$def binary_search(nums, target):
    low = 0
    high = len(nums) - 1
    while low < high:
        mid = (low + high) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1$$,
    $$def binary_search(nums, target):
    low = 0
    high = len(nums) - 1
    while low <= high:
        mid = (low + high) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            low = mid + 1
        else:
            high = mid - 1
    return -1$$,
    $$binary_search(nums, target) should return the index of target in a sorted list, or -1 if it isn't there.$$,
    $$It works for most values but returns -1 for some that are definitely present — searching for 9 in [1,3,5,7,9] gives -1.$$,
    $$The loop condition `low < high` exits when low and high meet, so the single remaining candidate is never checked. Binary search must keep going while the search window still contains one element, which means `low <= high`. Bugs like this hide well because they only show up when the target lands on the final narrowing step.$$,
    $$[{"input":[[1,3,5,7,9],9],"expected_output":4},{"input":[[1,3,5,7,9],1],"expected_output":0},{"input":[[1,3,5,7,9],5],"expected_output":2},{"input":[[1,3,5],4],"expected_output":-1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It only fails for certain targets. What do those targets have in common?$$ from new_challenge
union all
select id, 2, $$Think about the moment when low and high become equal — does the loop still run?$$ from new_challenge
union all
select id, 3, $$When low == high there is still one unchecked element. The condition should be low <= high.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$First item's name crashes on an empty list$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$easy$$,
    $$firstItemName$$,
    $$function firstItemName(items) {
    return items[0].name;
}$$,
    $$function firstItemName(items) {
    return items.length > 0 ? items[0].name : "None";
}$$,
    $$firstItemName(items) should return the name of the first item, or "None" when the list is empty.$$,
    $$Passing an empty array throws "Cannot read properties of undefined (reading 'name')".$$,
    $$Indexing past the end of an array gives undefined rather than throwing, so the error surfaces one step later when .name is read from it. Guard on the array being non-empty before reaching into it. The lesson generalises: in JavaScript an out-of-range index fails silently, and you find out at the next property access.$$,
    $$[{"input":[[{"name":"first"},{"name":"second"}]],"expected_output":"first"},{"input":[[]],"expected_output":"None"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What does items[0] evaluate to when the array has nothing in it?$$ from new_challenge
union all
select id, 2, $$The return line assumes there is always a first item.$$ from new_challenge
union all
select id, 3, $$Check items.length before reading items[0].name, and return "None" otherwise.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Optional middle name breaks the full name$$,
    $$python$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$full_name$$,
    $$def full_name(user):
    return user["first"] + " " + user["middle"] + " " + user["last"]$$,
    $$def full_name(user):
    parts = [user["first"], user.get("middle"), user["last"]]
    return " ".join(p for p in parts if p)$$,
    $$full_name(user) should join a user's name parts with single spaces, skipping the middle name when there isn't one.$$,
    $$A user without a "middle" key crashes with KeyError, and one whose middle name is None crashes with a TypeError.$$,
    $$The code assumes every optional field is both present and a string. Two separate failure modes hide here: a missing key raises KeyError, and a present-but-None value fails to concatenate. Collecting the parts and filtering out the falsy ones handles both at once, and keeps the spacing correct instead of leaving a double space.$$,
    $$[{"input":[{"first":"Ada","middle":"Byron","last":"Lovelace"}],"expected_output":"Ada Byron Lovelace"},{"input":[{"first":"Alan","last":"Turing"}],"expected_output":"Alan Turing"},{"input":[{"first":"Grace","middle":null,"last":"Hopper"}],"expected_output":"Grace Hopper"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$There are two different ways this breaks — try a user with no middle key, then one whose middle is None.$$ from new_challenge
union all
select id, 2, $$Both failures come from the same line assuming every part exists and is a string.$$ from new_challenge
union all
select id, 3, $$Gather the parts into a list, drop the empty ones, and " ".join() what remains.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Total score comes out as NaN$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$sumScores$$,
    $$function sumScores(players) {
    let total = 0;
    for (const player of players) {
        total += player.score;
    }
    return total;
}$$,
    $$function sumScores(players) {
    let total = 0;
    for (const player of players) {
        total += player.score ?? 0;
    }
    return total;
}$$,
    $$sumScores(players) should add up every player's score, treating a player with no score as 0.$$,
    $$As soon as one player is missing a score, the total becomes NaN instead of a number.$$,
    $$Reading a missing property gives undefined, and undefined + number is NaN. Worse, NaN is contagious: once it enters the running total every later addition stays NaN, so one bad record poisons the whole result. Default the value at the point you read it.$$,
    $$[{"input":[[{"score":10},{"score":20}]],"expected_output":30},{"input":[[{"score":10},{},{"score":5}]],"expected_output":15},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What is the value of player.score for a player object with no score property?$$ from new_challenge
union all
select id, 2, $$Once the total becomes NaN it never recovers — look at what is being added.$$ from new_challenge
union all
select id, 3, $$Use player.score ?? 0 so a missing score contributes zero instead of undefined.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Leap year check gets century years wrong$$,
    $$python$$,
    $$logic_error$$,
    $$medium$$,
    $$is_leap_year$$,
    $$def is_leap_year(year):
    return year % 4 == 0 and year % 100 != 0$$,
    $$def is_leap_year(year):
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)$$,
    $$is_leap_year(year) should return True for leap years: divisible by 4, except centuries, unless divisible by 400.$$,
    $$is_leap_year(2000) returns False, even though 2000 was a leap year.$$,
    $$The rule has three parts and the code only implements two. Years divisible by 100 are excluded — correct for 1900 — but the exception to that exception is missing: years divisible by 400 are leap years after all. Whenever a spec says 'except… unless…', make sure every clause made it into the code.$$,
    $$[{"input":[2000],"expected_output":true},{"input":[1900],"expected_output":false},{"input":[2024],"expected_output":true},{"input":[2023],"expected_output":false}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Test a year divisible by 400, like 2000. What should it be, and what do you get?$$ from new_challenge
union all
select id, 2, $$The rule has three clauses; the code has two.$$ from new_challenge
union all
select id, 3, $$Add the exception: divisible by 400 makes it a leap year even though it is divisible by 100.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Free shipping threshold is off by a cent$$,
    $$javascript$$,
    $$logic_error$$,
    $$easy$$,
    $$qualifiesForFreeShipping$$,
    $$function qualifiesForFreeShipping(total) {
    return total > 50;
}$$,
    $$function qualifiesForFreeShipping(total) {
    return total >= 50;
}$$,
    $$qualifiesForFreeShipping(total) should return true when the order total is 50 or more — spending exactly 50 qualifies.$$,
    $$An order of exactly 50 returns false, so customers hitting the threshold are still charged.$$,
    $$'50 or more' includes 50 itself, which means >= rather than >. Boundary conditions are where requirements and code most often drift apart, and they rarely show up in casual testing because people try 49 and 51, not 50. When a spec says 'at least' or 'or more', the comparison is inclusive.$$,
    $$[{"input":[50],"expected_output":true},{"input":[49.99],"expected_output":false},{"input":[75],"expected_output":true}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try an order for exactly the threshold amount.$$ from new_challenge
union all
select id, 2, $$The comparison operator on the return line excludes one value it shouldn't.$$ from new_challenge
union all
select id, 3, $$"50 or more" includes 50, so use >= instead of >.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Grade boundaries return the wrong letter$$,
    $$python$$,
    $$logic_error$$,
    $$medium$$,
    $$grade$$,
    $$def grade(score):
    if score >= 60:
        return "D"
    elif score >= 70:
        return "C"
    elif score >= 80:
        return "B"
    elif score >= 90:
        return "A"
    return "F"$$,
    $$def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    return "F"$$,
    $$grade(score) should return "A" for 90+, "B" for 80-89, "C" for 70-79, "D" for 60-69, and "F" below 60.$$,
    $$A score of 95 returns "D" instead of "A".$$,
    $$In an if/elif chain the first matching branch wins, so the order of the conditions is part of the logic. Because 95 >= 60 is true, the chain stops at the very first branch and never reaches the check for 90. Overlapping ranges must be tested from the most restrictive to the least — highest threshold first.$$,
    $$[{"input":[95],"expected_output":"A"},{"input":[85],"expected_output":"B"},{"input":[72],"expected_output":"C"},{"input":[45],"expected_output":"F"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Walk through what happens for a score of 95, condition by condition.$$ from new_challenge
union all
select id, 2, $$Every branch after the first is unreachable for high scores. Why?$$ from new_challenge
union all
select id, 3, $$In an if/elif chain the first true branch wins — check the highest threshold first.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Digit sum never finishes$$,
    $$python$$,
    $$infinite_loop$$,
    $$medium$$,
    $$sum_digits$$,
    $$def sum_digits(n):
    total = 0
    while n > 0:
        total += n % 10
    return total$$,
    $$def sum_digits(n):
    total = 0
    while n > 0:
        total += n % 10
        n //= 10
    return total$$,
    $$sum_digits(n) should add up the digits of a number, so sum_digits(123) gives 6.$$,
    $$Calling sum_digits(123) hangs and never returns.$$,
    $$The loop reads the last digit with n % 10 but never removes it, so n keeps its original value and the condition n > 0 stays true forever. Digit-extraction loops need both halves: read the last digit, then drop it with integer division. Any while loop should make you ask what changes the condition.$$,
    $$[{"input":[123],"expected_output":6},{"input":[9],"expected_output":9},{"input":[4070],"expected_output":11}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The loop condition depends on n. Does anything in the body change n?$$ from new_challenge
union all
select id, 2, $$You read the last digit, but never remove it.$$ from new_challenge
union all
select id, 3, $$Add n //= 10 after the addition so the number shrinks each pass.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Reversing a string hangs the tab$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$medium$$,
    $$reverseString$$,
    $$function reverseString(text) {
    let out = "";
    let i = text.length - 1;
    while (i >= 0) {
        out += text[i];
    }
    return out;
}$$,
    $$function reverseString(text) {
    let out = "";
    let i = text.length - 1;
    while (i >= 0) {
        out += text[i];
        i--;
    }
    return out;
}$$,
    $$reverseString(text) should return the string backwards, so "abc" becomes "cba".$$,
    $$Calling reverseString("abc") freezes and never returns a value.$$,
    $$The index i is initialised and tested but never decremented, so the same character is appended forever and i >= 0 never becomes false. Manual index loops need three pieces — initialise, test, and step — and it's the step that's easiest to leave out when the loop body is doing something interesting.$$,
    $$[{"input":["abc"],"expected_output":"cba"},{"input":["a"],"expected_output":"a"},{"input":["debug"],"expected_output":"gubed"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which variable does the loop condition depend on, and where is it changed?$$ from new_challenge
union all
select id, 2, $$The loop body appends a character but never moves the index.$$ from new_challenge
union all
select id, 3, $$Add i-- inside the loop so i eventually drops below 0.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Duplicate removal spins forever$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$hard$$,
    $$dedupe$$,
    $$function dedupe(arr) {
    const out = [];
    let i = 0;
    while (i < arr.length) {
        if (!out.includes(arr[i])) {
            out.push(arr[i]);
        }
    }
    return out;
}$$,
    $$function dedupe(arr) {
    const out = [];
    let i = 0;
    while (i < arr.length) {
        if (!out.includes(arr[i])) {
            out.push(arr[i]);
        }
        i++;
    }
    return out;
}$$,
    $$dedupe(arr) should return the array with duplicates removed, keeping the first occurrence of each value.$$,
    $$Calling dedupe([1,2,2,3]) hangs — it never gets past the first element.$$,
    $$The index i is never incremented, so the loop re-tests position 0 forever — the first item gets added once, then the `includes` check keeps rejecting it while i stays put. A for...of loop would have advanced automatically; a manual while loop needs you to step the index yourself, and it's easy to forget when the body already has an if inside it.$$,
    $$[{"input":[[1,2,2,3]],"expected_output":[1,2,3]},{"input":[[1,1,1]],"expected_output":[1]},{"input":[[]],"expected_output":[]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Trace the first two iterations by hand. What is i each time?$$ from new_challenge
union all
select id, 2, $$The loop condition depends on i, and nothing in the body changes it.$$ from new_challenge
union all
select id, 3, $$Add i++ at the end of the loop body so it advances through the array.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Sorting numbers puts 10 before 9$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$sortNumbers$$,
    $$function sortNumbers(nums) {
    return nums.sort();
}$$,
    $$function sortNumbers(nums) {
    return nums.sort((a, b) => a - b);
}$$,
    $$sortNumbers(nums) should return the numbers sorted from smallest to largest.$$,
    $$sortNumbers([10, 9, 100, 1]) returns [1, 10, 100, 9] — 9 ends up last.$$,
    $$Array.sort() converts each element to a string and sorts lexicographically, so "10" sorts before "9" the same way "apple" sorts before "banana". Numeric sorting needs an explicit comparator, (a, b) => a - b. The default behaviour surprises almost everyone because it looks right for single-digit arrays.$$,
    $$[{"input":[[10,9,100,1]],"expected_output":[1,9,10,100]},{"input":[[3,1,2]],"expected_output":[1,2,3]},{"input":[[20,3]],"expected_output":[3,20]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Look closely at where 9 ends up relative to 10 and 100. Does that ordering look like anything else you know?$$ from new_challenge
union all
select id, 2, $$sort() with no arguments does not compare numbers the way you'd expect.$$ from new_challenge
union all
select id, 3, $$Pass a comparator: nums.sort((a, b) => a - b).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Average always comes back as a whole number$$,
    $$python$$,
    $$type_error$$,
    $$easy$$,
    $$average$$,
    $$def average(nums):
    return sum(nums) // len(nums)$$,
    $$def average(nums):
    return sum(nums) / len(nums)$$,
    $$average(nums) should return the mean of a list of numbers, including any fractional part.$$,
    $$average([1, 2]) returns 1 instead of 1.5 — the decimal part disappears.$$,
    $$// is floor division: it discards the remainder and returns a whole number. Regular division with / keeps the fractional part. The two look almost identical when skimming code, and the bug only shows up for inputs that don't divide evenly — which is exactly why [2, 4] would have passed a casual test.$$,
    $$[{"input":[[1,2]],"expected_output":1.5},{"input":[[2,4]],"expected_output":3},{"input":[[1,2,4]],"expected_output":2.3333333333333335}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try a list whose values don't divide evenly and compare with what you'd expect.$$ from new_challenge
union all
select id, 2, $$There are two division operators in Python. Which one is used here?$$ from new_challenge
union all
select id, 3, $$// floors the result. Use / to keep the fractional part.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Counting votes concatenates instead of adding$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$countVotes$$,
    $$function countVotes(entries) {
    let total = 0;
    for (const entry of entries) {
        total += entry.votes;
    }
    return total;
}$$,
    $$function countVotes(entries) {
    let total = 0;
    for (const entry of entries) {
        total += Number(entry.votes);
    }
    return total;
}$$,
    $$countVotes(entries) should add up the votes field of every entry and return the numeric total.$$,
    $$countVotes with votes of "3" and "4" returns "034" instead of 7 — the digits are strung together.$$,
    $$The vote counts arrive as strings, and + means concatenation as soon as either operand is a string. Because the running total becomes a string on the very first addition, every later one concatenates too. Convert at the boundary where untrusted data enters your arithmetic, with Number() or parseInt(value, 10).$$,
    $$[{"input":[[{"votes":"3"},{"votes":"4"}]],"expected_output":7},{"input":[[{"votes":"10"},{"votes":"5"},{"votes":"1"}]],"expected_output":16},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What type is entry.votes? Look at the quotes in the test cases.$$ from new_challenge
union all
select id, 2, $$In JavaScript + does two different jobs depending on the operand types.$$ from new_challenge
union all
select id, 3, $$Wrap the value in Number() before adding it to the total.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Every callback reports the same index$$,
    $$javascript$$,
    $$scope_error$$,
    $$hard$$,
    $$collectIndexes$$,
    $$function collectIndexes(n) {
    const out = [];
    const pending = [];
    for (var i = 0; i < n; i++) {
        pending.push(new Promise((resolve) => {
            setTimeout(() => { out.push(i); resolve(); }, 1);
        }));
    }
    return Promise.all(pending).then(() => out);
}$$,
    $$function collectIndexes(n) {
    const out = [];
    const pending = [];
    for (let i = 0; i < n; i++) {
        pending.push(new Promise((resolve) => {
            setTimeout(() => { out.push(i); resolve(); }, 1);
        }));
    }
    return Promise.all(pending).then(() => out);
}$$,
    $$collectIndexes(n) should schedule one callback per index and resolve to the list of indexes, so collectIndexes(3) gives [0, 1, 2].$$,
    $$collectIndexes(3) resolves to [3, 3, 3] — every callback reports the final value.$$,
    $$`var` is function-scoped, so all three callbacks close over the *same* i, and by the time the timeouts fire the loop has finished and i is 3. `let` is block-scoped and creates a fresh binding per iteration, so each callback captures its own value. This is the single most famous JavaScript closure bug, and it only appears when the callback runs later than the loop.$$,
    $$[{"input":[3],"expected_output":[0,1,2]},{"input":[1],"expected_output":[0]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The callbacks run after the loop has already finished. What is i by then?$$ from new_challenge
union all
select id, 2, $$All the callbacks are sharing one variable rather than each getting their own.$$ from new_challenge
union all
select id, 3, $$var is function-scoped; let creates a new binding per iteration. Change var i to let i.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Shopping list remembers items between calls$$,
    $$python$$,
    $$scope_error$$,
    $$hard$$,
    $$make_baskets$$,
    $$def add_item(item, basket=[]):
    basket.append(item)
    return basket

def make_baskets(first, second):
    return [add_item(first), add_item(second)]$$,
    $$def add_item(item, basket=None):
    if basket is None:
        basket = []
    basket.append(item)
    return basket

def make_baskets(first, second):
    return [add_item(first), add_item(second)]$$,
    $$make_baskets(first, second) should start a separate basket for each item, so make_baskets("apple", "bread") gives [["apple"], ["bread"]].$$,
    $$make_baskets("apple", "bread") returns [["apple", "bread"], ["apple", "bread"]] — both baskets hold both items.$$,
    $$A default argument is evaluated once, when the function is defined, not on every call. So every call that omits `basket` shares one list that keeps growing for the lifetime of the program. The fix is the standard Python idiom: default to None and build a new list inside the function. Never use a mutable value as a default argument.$$,
    $$[{"input":["apple","bread"],"expected_output":[["apple"],["bread"]]},{"input":["milk","eggs"],"expected_output":[["milk"],["eggs"]]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Both baskets contain the same two items. Are they even two different lists?$$ from new_challenge
union all
select id, 2, $$When exactly does Python evaluate the default value in a function signature — once, or on every call?$$ from new_challenge
union all
select id, 3, $$Default to None and create the list inside the function body.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Discounted price is unreachable outside the branch$$,
    $$javascript$$,
    $$scope_error$$,
    $$medium$$,
    $$finalPrice$$,
    $$function finalPrice(price, isMember) {
    if (isMember) {
        const discounted = price * 0.9;
    } else {
        const discounted = price;
    }
    return discounted;
}$$,
    $$function finalPrice(price, isMember) {
    let discounted;
    if (isMember) {
        discounted = price * 0.9;
    } else {
        discounted = price;
    }
    return discounted;
}$$,
    $$finalPrice(price, isMember) should apply a 10% discount for members and return the price to pay.$$,
    $$Every call throws: ReferenceError: discounted is not defined.$$,
    $$`const` and `let` are block-scoped, so a variable declared inside an if or else block does not exist outside it — the two declarations here are separate variables, both gone by the time the return runs. Declare once in the enclosing scope and assign inside the branches.$$,
    $$[{"input":[100,true],"expected_output":90},{"input":[100,false],"expected_output":100},{"input":[50,true],"expected_output":45}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which block is discounted declared in, and which block is it read from?$$ from new_challenge
union all
select id, 2, $$There are two separate declarations here, not one variable assigned twice.$$ from new_challenge
union all
select id, 3, $$Declare `let discounted;` before the if, then assign inside each branch.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$forEach finishes before the work does$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$doubleAll$$,
    $$function fetchDouble(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n * 2), 5));
}

async function doubleAll(nums) {
    const results = [];
    nums.forEach(async (n) => {
        results.push(await fetchDouble(n));
    });
    return results;
}$$,
    $$function fetchDouble(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n * 2), 5));
}

async function doubleAll(nums) {
    const results = [];
    for (const n of nums) {
        results.push(await fetchDouble(n));
    }
    return results;
}$$,
    $$doubleAll(nums) should resolve to a list with every number doubled.$$,
    $$doubleAll([1, 2, 3]) resolves to an empty array instead of [2, 4, 6].$$,
    $$forEach ignores the promise its callback returns, so it fires all three callbacks and moves on immediately — the function returns while every await is still pending. Array.forEach is simply not async-aware. Use a for...of loop with await inside, or Promise.all with map when the work can run in parallel.$$,
    $$[{"input":[[1,2,3]],"expected_output":[2,4,6]},{"input":[[5]],"expected_output":[10]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The results array is empty, not wrong — so the pushes hadn't happened yet when it was returned.$$ from new_challenge
union all
select id, 2, $$Does forEach wait for an async callback to finish before moving on?$$ from new_challenge
union all
select id, 3, $$forEach ignores returned promises. Use a for...of loop with await, or Promise.all(nums.map(...)).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Missing await turns the total into text$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$sumDelayed$$,
    $$function delay(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n), 1));
}

async function sumDelayed(nums) {
    let total = 0;
    for (const n of nums) {
        total += delay(n);
    }
    return total;
}$$,
    $$function delay(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n), 1));
}

async function sumDelayed(nums) {
    let total = 0;
    for (const n of nums) {
        total += await delay(n);
    }
    return total;
}$$,
    $$sumDelayed(nums) should add up numbers that each arrive asynchronously, resolving to the total.$$,
    $$sumDelayed([1, 2, 3]) resolves to "0[object Promise][object Promise][object Promise]" instead of 6.$$,
    $$delay() returns a Promise, and without await you add the Promise object itself rather than its resolved value. JavaScript coerces it to the string "[object Promise]", so the total silently becomes text instead of throwing. A result containing "[object Promise]" is almost always a missing await.$$,
    $$[{"input":[[1,2,3]],"expected_output":6},{"input":[[10]],"expected_output":10},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Look at the exact text in the result — what type is being added to the total?$$ from new_challenge
union all
select id, 2, $$delay() hands back a Promise, not a number.$$ from new_challenge
union all
select id, 3, $$Add await before delay(n) so the resolved value is what gets added.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$map returns promises instead of values$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$wordLengths$$,
    $$async function wordLengths(words) {
    return words.map(async (word) => word.length);
}$$,
    $$async function wordLengths(words) {
    return Promise.all(words.map(async (word) => word.length));
}$$,
    $$wordLengths(words) should resolve to a list of each word's length.$$,
    $$wordLengths(["abc", "defg"]) resolves to [{}, {}] instead of [3, 4].$$,
    $$An async callback always returns a Promise, so map produces an array *of Promises*, and awaiting the outer function only unwraps one layer — not the promises inside the array. Promise.all turns an array of promises into a promise of an array, which is what you actually want.$$,
    $$[{"input":[["abc","defg"]],"expected_output":[3,4]},{"input":[["hi"]],"expected_output":[2]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The array has the right number of entries but the wrong contents. What are those entries?$$ from new_challenge
union all
select id, 2, $$An async function always returns a Promise — even a one-line one inside map.$$ from new_challenge
union all
select id, 3, $$Wrap the mapped array in Promise.all() so every inner promise resolves.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Copying settings changes the original$$,
    $$python$$,
    $$other$$,
    $$hard$$,
    $$with_theme$$,
    $$def with_theme(settings, theme):
    updated = settings.copy()
    updated["display"]["theme"] = theme
    return updated["display"]["theme"] + "|" + settings["display"]["theme"]$$,
    $$import copy

def with_theme(settings, theme):
    updated = copy.deepcopy(settings)
    updated["display"]["theme"] = theme
    return updated["display"]["theme"] + "|" + settings["display"]["theme"]$$,
    $$with_theme(settings, theme) should return a copy with a new theme, leaving the original untouched. It returns "newtheme|originaltheme" so you can see both.$$,
    $$Both halves come back the same — "dark|dark" — showing the original was modified too.$$,
    $$dict.copy() is a shallow copy: the new dict has its own top level, but the nested dicts are the *same objects* as the original's. Mutating settings['display'] therefore changes both. copy.deepcopy() recursively copies the nested structures. Shallow-copy bugs are nasty because the code looks defensive and passes any test using flat data.$$,
    $$[{"input":[{"display":{"theme":"light"}},"dark"],"expected_output":"dark|light"},{"input":[{"display":{"theme":"blue"}},"red"],"expected_output":"red|blue"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The original was supposed to stay unchanged. Check whether .copy() protects nested values.$$ from new_challenge
union all
select id, 2, $$copy() duplicates the outer dict only — the inner dict is shared between both.$$ from new_challenge
union all
select id, 3, $$Use copy.deepcopy(settings) so nested dictionaries are copied too.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Removing items skips every other one$$,
    $$python$$,
    $$other$$,
    $$hard$$,
    $$remove_evens$$,
    $$def remove_evens(nums):
    for n in nums:
        if n % 2 == 0:
            nums.remove(n)
    return nums$$,
    $$def remove_evens(nums):
    return [n for n in nums if n % 2 != 0]$$,
    $$remove_evens(nums) should return the list with all even numbers removed.$$,
    $$remove_evens([2, 4, 6, 1]) returns [4, 1] — one of the even numbers survives.$$,
    $$Removing from a list while iterating over it shifts every later element down one position, but the loop's internal index still advances — so the element that slid into the removed slot is skipped entirely. Never mutate a collection you're iterating. Build a new list instead, which a comprehension does cleanly.$$,
    $$[{"input":[[2,4,6,1]],"expected_output":[1]},{"input":[[1,3]],"expected_output":[1,3]},{"input":[[2,2]],"expected_output":[]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which even number survives, and where was it sitting relative to the one removed before it?$$ from new_challenge
union all
select id, 2, $$The list is being changed while the loop is walking through it.$$ from new_challenge
union all
select id, 3, $$Build a new list with a comprehension instead of removing from the one you're iterating.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Money totals gain a fraction of a cent$$,
    $$javascript$$,
    $$other$$,
    $$medium$$,
    $$addPrices$$,
    $$function addPrices(a, b) {
    return a + b;
}$$,
    $$function addPrices(a, b) {
    return Math.round((a + b) * 100) / 100;
}$$,
    $$addPrices(a, b) should add two prices in dollars and return a value correct to the cent.$$,
    $$addPrices(0.1, 0.2) returns 0.30000000000000004 instead of 0.3.$$,
    $$Floating-point numbers can't represent 0.1 or 0.2 exactly in binary, so the sum lands a hair off. This isn't a JavaScript quirk — it's how IEEE-754 works in nearly every language. For money, either round to the required precision after arithmetic, or work in integer cents and divide only when displaying.$$,
    $$[{"input":[0.1,0.2],"expected_output":0.3},{"input":[1.005,2.005],"expected_output":3.01},{"input":[5,5],"expected_output":10}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Look at the exact digits in the result — how far off is it, really?$$ from new_challenge
union all
select id, 2, $$This is about how computers store decimal fractions in binary.$$ from new_challenge
union all
select id, 3, $$Round after the arithmetic: Math.round((a + b) * 100) / 100.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Flatten only unwraps one level$$,
    $$javascript$$,
    $$other$$,
    $$medium$$,
    $$flattenDeep$$,
    $$function flattenDeep(arr) {
    return arr.flat();
}$$,
    $$function flattenDeep(arr) {
    return arr.flat(Infinity);
}$$,
    $$flattenDeep(arr) should flatten a nested array completely, however many levels deep it goes.$$,
    $$flattenDeep([1, [2, [3, [4]]]]) returns [1, 2, [3, [4]]] — still nested.$$,
    $$Array.flat() defaults to a depth of 1, so it removes exactly one level of nesting no matter how deep the structure is. Passing Infinity flattens all the way down. Defaults like this are easy to miss because the shallow case works perfectly, and the bug only appears once the data gets deeper.$$,
    $$[{"input":[[1,[2,[3,[4]]]]],"expected_output":[1,2,3,4]},{"input":[[1,[2]]],"expected_output":[1,2]},{"input":[[[[5]]]],"expected_output":[5]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It worked partially — exactly how many levels did it remove?$$ from new_challenge
union all
select id, 2, $$flat() takes an argument you're not passing.$$ from new_challenge
union all
select id, 3, $$flat() defaults to depth 1. Pass Infinity to flatten completely.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Uppercasing a string does nothing$$,
    $$python$$,
    $$other$$,
    $$easy$$,
    $$shout$$,
    $$def shout(text):
    text.upper()
    return text$$,
    $$def shout(text):
    return text.upper()$$,
    $$shout(text) should return the text in uppercase, so "hello" becomes "HELLO".$$,
    $$shout("hello") returns "hello" unchanged.$$,
    $$Strings are immutable in Python, so .upper() cannot modify text in place — it returns a new string, and here that return value is discarded. Any string method that looks like it 'does something' actually hands back a new string you have to keep. The same trap applies to .strip(), .replace() and friends.$$,
    $$[{"input":["hello"],"expected_output":"HELLO"},{"input":["Debug"],"expected_output":"DEBUG"},{"input":[""],"expected_output":""}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The call to upper() runs — so where does its result go?$$ from new_challenge
union all
select id, 2, $$Strings in Python cannot be changed in place.$$ from new_challenge
union all
select id, 3, $$upper() returns a new string. Return it directly instead of discarding it.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Capitalise repeats the first letter$$,
    $$javascript$$,
    $$off_by_one$$,
    $$easy$$,
    $$capitalize$$,
    $$function capitalize(word) {
    return word.charAt(0).toUpperCase() + word.slice(0);
}$$,
    $$function capitalize(word) {
    return word.charAt(0).toUpperCase() + word.slice(1);
}$$,
    $$capitalize(word) should upper-case the first letter, so "debug" becomes "Debug".$$,
    $$capitalize("debug") returns "Ddebug" — the first letter appears twice.$$,
    $$slice(0) returns the whole string, including the character that was already upper-cased and prepended. It needs to start from index 1 so the remainder excludes the first letter. An index of 0 where 1 was meant is one of the quietest off-by-one bugs, because the output looks almost right.$$,
    $$[{"input":["debug"],"expected_output":"Debug"},{"input":["a"],"expected_output":"A"},{"input":["hello world"],"expected_output":"Hello world"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Compare the output to the input letter by letter. What got duplicated?$$ from new_challenge
union all
select id, 2, $$The slice is returning more of the string than intended.$$ from new_challenge
union all
select id, 3, $$The first character is already handled, so the rest should start at index 1: slice(1).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Grouping keeps only the last match$$,
    $$javascript$$,
    $$logic_error$$,
    $$medium$$,
    $$groupByLength$$,
    $$function groupByLength(words) {
    const groups = {};
    for (const word of words) {
        groups[word.length] = [word];
    }
    return groups;
}$$,
    $$function groupByLength(words) {
    const groups = {};
    for (const word of words) {
        if (!groups[word.length]) {
            groups[word.length] = [];
        }
        groups[word.length].push(word);
    }
    return groups;
}$$,
    $$groupByLength(words) should group words by their length, so ["ab","cd","x"] gives {"1":["x"],"2":["ab","cd"]}.$$,
    $$Each group only ever holds one word — ["ab","cd"] gives {"2":["cd"]}, losing "ab".$$,
    $$Assigning a fresh single-item array replaces whatever was already stored under that key, so each group only keeps the last word seen. Grouping needs accumulation: create the array once if it's missing, then push onto it. The distinction between assigning and appending is what separates a grouping from a lookup.$$,
    $$[{"input":[["ab","cd","x"]],"expected_output":{"1":["x"],"2":["ab","cd"]}},{"input":[["a"]],"expected_output":{"1":["a"]}}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Each group holds exactly one word. Which one — the first or the last?$$ from new_challenge
union all
select id, 2, $$The assignment inside the loop overwrites whatever was there before.$$ from new_challenge
union all
select id, 3, $$Create the array only if it doesn't exist yet, then push onto it instead of assigning.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Word count breaks on double spaces$$,
    $$python$$,
    $$logic_error$$,
    $$easy$$,
    $$count_words$$,
    $$def count_words(text):
    return len(text.split(" "))$$,
    $$def count_words(text):
    return len(text.split())$$,
    $$count_words(text) should count the words in a string, however much whitespace separates them.$$,
    $$count_words("hello  world") returns 3 instead of 2 — the double space is counted as a word.$$,
    $$split(" ") splits on every single space, so consecutive spaces produce empty strings between them. Calling split() with no argument splits on any run of whitespace and discards the empties — which is almost always what you want for words. The two forms look interchangeable until the input has irregular spacing.$$,
    $$[{"input":["hello  world"],"expected_output":2},{"input":["one two three"],"expected_output":3},{"input":["single"],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try a string with two spaces in a row and print the list that split produces.$$ from new_challenge
union all
select id, 2, $$Splitting on a literal single space leaves empty strings behind.$$ from new_challenge
union all
select id, 3, $$Call split() with no arguments — it splits on any whitespace and drops the empties.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Merging settings mutates the defaults$$,
    $$python$$,
    $$other$$,
    $$medium$$,
    $$merge_settings$$,
    $$def merge_settings(defaults, overrides):
    defaults.update(overrides)
    return str(defaults.get("mode")) + "|" + str(len(defaults))$$,
    $$def merge_settings(defaults, overrides):
    merged = dict(defaults)
    merged.update(overrides)
    return str(merged.get("mode")) + "|" + str(len(defaults))$$,
    $$merge_settings(defaults, overrides) should merge overrides on top of defaults without changing the defaults. It returns "mode|numberOfDefaultKeys" so you can see both.$$,
    $$The key count reflects the merged result rather than the original defaults — merging a brand-new key into a one-key defaults dict reports 2 instead of 1.$$,
    $$dict.update() modifies the dictionary it's called on, in place. Since `defaults` was passed in by the caller, the caller's dictionary is changed too — a side effect the function name doesn't advertise. Copy first with dict(defaults), then update the copy. Functions that quietly mutate their arguments are a classic source of action-at-a-distance bugs.$$,
    $$[{"input":[{"mode":"light"},{"size":"big"}],"expected_output":"light|1"},{"input":[{"mode":"light"},{"mode":"dark","size":"big"}],"expected_output":"dark|1"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The merge itself is right — check whether the defaults you passed in survived unchanged.$$ from new_challenge
union all
select id, 2, $$update() works in place on the dictionary it is called on.$$ from new_challenge
union all
select id, 3, $$Copy first with dict(defaults), then update the copy and return that.$$ from new_challenge;
