-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 5 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Binary search that stops narrowing$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$hard$$,
    $$indexOfValue$$,
    $$function indexOfValue(sorted, target) {
    let low = 0;
    let high = sorted.length - 1;
    while (low <= high) {
        const mid = Math.floor((low + high) / 2);
        if (sorted[mid] === target) {
            return mid;
        }
        if (sorted[mid] < target) {
            low = mid;
        } else {
            high = mid;
        }
    }
    return -1;
}$$,
    $$function indexOfValue(sorted, target) {
    let low = 0;
    let high = sorted.length - 1;
    while (low <= high) {
        const mid = Math.floor((low + high) / 2);
        if (sorted[mid] === target) {
            return mid;
        }
        if (sorted[mid] < target) {
            low = mid + 1;
        } else {
            high = mid - 1;
        }
    }
    return -1;
}$$,
    $$indexOfValue(sorted, target) should return the index of target in a sorted array, or -1 if it is absent.$$,
    $$Finding a value that IS present usually works, but searching for a missing value hangs forever.$$,
    $$Setting low = mid (rather than mid + 1) leaves mid inside the search range, so when low and high end up adjacent the midpoint stops changing and the range never shrinks. Since mid was already ruled out by the equality check above, it is safe — and necessary — to exclude it. Every binary search needs the range to get strictly smaller each iteration; if it can stay the same size, the loop can spin. The tell is that it only hangs when the target is absent, because a present target escapes through the early return before the range collapses.$$,
    $$[{"input":[[1,3,5,7],5],"expected_output":2},{"input":[[1,3,5,7],4],"expected_output":-1},{"input":[[2],9],"expected_output":-1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It hangs only when the value is missing. What lets a successful search escape?$$ from new_challenge
union all
select id, 2, $$Print low, high and mid each iteration. Do they keep changing?$$ from new_challenge
union all
select id, 3, $$mid has already been ruled out, so exclude it: low = mid + 1 and high = mid - 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Index only advances on a match$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$medium$$,
    $$countUppercase$$,
    $$function countUppercase(text) {
    let i = 0;
    let count = 0;
    while (i < text.length) {
        if (text[i] === text[i].toUpperCase()) {
            count = count + 1;
            i = i + 1;
        }
    }
    return count;
}$$,
    $$function countUppercase(text) {
    let i = 0;
    let count = 0;
    while (i < text.length) {
        if (text[i] === text[i].toUpperCase()) {
            count = count + 1;
        }
        i = i + 1;
    }
    return count;
}$$,
    $$countUppercase(text) should count the uppercase letters, so countUppercase("aBc") returns 1.$$,
    $$countUppercase("ABC") returns 3, but countUppercase("aBc") never finishes.$$,
    $$The increment sits INSIDE the if, so the index only moves when the character matches. Hit a lowercase letter and the loop re-examines that same character forever. Advancing the cursor is the loop's own bookkeeping and belongs outside any conditional — it must happen on every iteration regardless of what the body decides. All-uppercase input hides the bug completely, which is a good reminder to test the case where the condition is false.$$,
    $$[{"input":["ABC"],"expected_output":3},{"input":["aBc"],"expected_output":1},{"input":["xyz"],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$All-uppercase input works. What happens on the first lowercase letter?$$ from new_challenge
union all
select id, 2, $$Which statements run when the if condition is false?$$ from new_challenge
union all
select id, 3, $$Move i = i + 1 outside the if so it runs every iteration.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Doubling loop that never doubles$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$easy$$,
    $$stepsToExceed$$,
    $$function stepsToExceed(limit) {
    let value = 1;
    let steps = 0;
    while (value <= limit) {
        steps = steps + 1;
    }
    return steps;
}$$,
    $$function stepsToExceed(limit) {
    let value = 1;
    let steps = 0;
    while (value <= limit) {
        value = value * 2;
        steps = steps + 1;
    }
    return steps;
}$$,
    $$stepsToExceed(limit) counts how many times you must double 1 before passing limit, so stepsToExceed(8) returns 4.$$,
    $$stepsToExceed(8) never returns — the page freezes.$$,
    $$The loop condition tests `value`, but nothing in the body ever changes it, so the condition is stuck true forever. Every while loop needs its body to make progress toward the condition becoming false. When a loop hangs, the first thing to check is which variable the condition depends on and whether the body actually modifies it — here `steps` changes but is not part of the condition, which is exactly the kind of near-miss that reads as correct.$$,
    $$[{"input":[8],"expected_output":4},{"input":[1],"expected_output":1},{"input":[100],"expected_output":7}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which variable does the while condition look at?$$ from new_challenge
union all
select id, 2, $$Does anything in the loop body change that variable?$$ from new_challenge
union all
select id, 3, $$`value` is never doubled. Add value = value * 2 inside the loop.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Cleaning double spaces never terminates$$,
    $$python$$,
    $$infinite_loop$$,
    $$medium$$,
    $$squash_spaces$$,
    $$def squash_spaces(text):
    while "  " in text:
        text.replace("  ", " ")
    return text$$,
    $$def squash_spaces(text):
    while "  " in text:
        text = text.replace("  ", " ")
    return text$$,
    $$squash_spaces(text) should collapse runs of spaces into one, so squash_spaces("a  b") returns "a b".$$,
    $$squash_spaces("a b") returns immediately, but squash_spaces("a  b") hangs forever.$$,
    $$Strings in Python are immutable, so .replace() cannot modify text in place — it returns a NEW string and leaves the original untouched. Discarding that return value means text still contains the double space, the while condition stays true, and the loop spins. Assigning the result back is the fix. The same trap applies to .strip(), .upper() and .lower(); the methods that DO mutate in place, like list.append() and list.sort(), return None instead — which is the clue that tells the two families apart.$$,
    $$[{"input":["a  b"],"expected_output":"a b"},{"input":["a b"],"expected_output":"a b"},{"input":["x   y"],"expected_output":"x y"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Input with no double space returns fine. What has to change for the loop to end?$$ from new_challenge
union all
select id, 2, $$Does text ever actually change?$$ from new_challenge
union all
select id, 3, $$str.replace returns a new string. Assign it back: text = text.replace(...).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Outer index advances only when a pair is found$$,
    $$python$$,
    $$infinite_loop$$,
    $$hard$$,
    $$count_pairs$$,
    $$def count_pairs(nums, target):
    count = 0
    i = 0
    while i < len(nums):
        j = i + 1
        while j < len(nums):
            if nums[i] + nums[j] == target:
                count += 1
                i += 1
            j += 1
    return count$$,
    $$def count_pairs(nums, target):
    count = 0
    i = 0
    while i < len(nums):
        j = i + 1
        while j < len(nums):
            if nums[i] + nums[j] == target:
                count += 1
            j += 1
        i += 1
    return count$$,
    $$count_pairs(nums, target) should count the pairs that add up to target, so count_pairs([1, 2, 3], 4) returns 1.$$,
    $$count_pairs([1, 2, 3], 5) hangs. It only returns when a pair happens to be found on every pass.$$,
    $$`i += 1` ended up inside the inner loop's if-branch, so the outer index only advances when a matching pair turns up. Once a pass finds nothing, i stays put and the outer loop repeats the same pass forever. The outer loop's counter belongs after the inner loop, at the outer loop's own indentation — this is a pure indentation bug, and Python's whitespace-as-syntax makes it easy to introduce and easy to miss. It also means the broken version double-counts when it does terminate, since advancing i mid-scan skips comparisons.$$,
    $$[{"input":[[1,2,3],4],"expected_output":1},{"input":[[1,2,3],5],"expected_output":1},{"input":[[1,1,1],2],"expected_output":3}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Print i at the top of the outer loop. Does it always move?$$ from new_challenge
union all
select id, 2, $$Look at the indentation of `i += 1` — which loop does it belong to?$$ from new_challenge
union all
select id, 3, $$i += 1 should sit after the inner while loop, at the outer loop's level.$$ from new_challenge;
