-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 3 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Method loses its object when passed as a callback$$,
    $$javascript$$,
    $$scope_error$$,
    $$hard$$,
    $$countAll$$,
    $$class Counter {
    constructor() {
        this.n = 0;
    }
    inc() {
        this.n = this.n + 1;
    }
}

function countAll(items) {
    const counter = new Counter();
    items.forEach(counter.inc);
    return counter.n;
}$$,
    $$class Counter {
    constructor() {
        this.n = 0;
    }
    inc() {
        this.n = this.n + 1;
    }
}

function countAll(items) {
    const counter = new Counter();
    items.forEach(() => counter.inc());
    return counter.n;
}$$,
    $$countAll(items) should count how many items were passed in, so countAll([1, 2, 3]) returns 3.$$,
    $$countAll([1, 2, 3]) throws "Cannot read properties of undefined (reading 'n')", even though counter is clearly defined.$$,
    $$`this` in JavaScript is decided by HOW a function is called, not where it was defined. Writing `counter.inc` extracts the bare function and forgets the object entirely — forEach then calls it with no receiver, so inside inc, `this` is undefined (class bodies are always strict mode). Wrapping it in an arrow, `() => counter.inc()`, preserves the call as a method call. counter.inc.bind(counter) works too. Any time you pass a method somewhere as a value — forEach, setTimeout, an event handler — you have to keep the receiver attached.$$,
    $$[{"input":[[1,2,3]],"expected_output":3},{"input":[[]],"expected_output":0},{"input":[["a","b"]],"expected_output":2}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The error says something is undefined. Inside inc(), what exactly is `this`?$$ from new_challenge
union all
select id, 2, $$Passing counter.inc hands over the function but not the object it belongs to.$$ from new_challenge
union all
select id, 3, $$Call it as a method: items.forEach(() => counter.inc()).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Hoisted var shadows the value you wanted$$,
    $$javascript$$,
    $$scope_error$$,
    $$hard$$,
    $$describe$$,
    $$const label = "global";

function describe(useLocal) {
    if (!useLocal) {
        return label;
    }
    var label = "local";
    return label;
}$$,
    $$const label = "global";

function describe(useLocal) {
    if (!useLocal) {
        return label;
    }
    var localLabel = "local";
    return localLabel;
}$$,
    $$describe(useLocal) should return "local" when useLocal is true and the outer "global" when it is false.$$,
    $$describe(false) throws "Cannot access 'label' before initialization" instead of returning "global".$$,
    $$`var label` is hoisted to the top of the whole function, so the inner declaration shadows the outer `label` everywhere inside describe — including in the early return that runs before the assignment. The outer constant becomes unreachable from this function entirely. This is why shadowing an outer name with var is dangerous: the shadow covers the entire function body, not just the lines after it. Rename the inner variable, or use let/const, which at least confines the shadow to its block.$$,
    $$[{"input":[true],"expected_output":"local"},{"input":[false],"expected_output":"global"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The outer `label` is a const with a value, so why is it "not initialized"?$$ from new_challenge
union all
select id, 2, $$Where does a `var` declaration actually take effect inside a function?$$ from new_challenge
union all
select id, 3, $$The inner var label shadows the outer one across the whole function. Give it a different name.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Constant used one line before it exists$$,
    $$javascript$$,
    $$scope_error$$,
    $$medium$$,
    $$priceWithFee$$,
    $$function priceWithFee(base) {
    const total = base + fee;
    const fee = 5;
    return total;
}$$,
    $$function priceWithFee(base) {
    const fee = 5;
    const total = base + fee;
    return total;
}$$,
    $$priceWithFee(base) should add a flat fee of 5 to the base price, so priceWithFee(10) returns 15.$$,
    $$priceWithFee(10) throws "Cannot access 'fee' before initialization".$$,
    $$let and const are hoisted, but they sit in the temporal dead zone until their declaration line actually runs — touching them before that is a ReferenceError rather than undefined. This is deliberate: it turns a silent bug into a loud one. (With var you would have got undefined and NaN, which is far harder to trace.) The fix is simply to declare before use. The error message names the variable, which makes this one of the friendlier errors to debug once you recognise the phrase.$$,
    $$[{"input":[10],"expected_output":15},{"input":[0],"expected_output":5},{"input":[2.5],"expected_output":7.5}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Read the two const lines in the order they execute.$$ from new_challenge
union all
select id, 2, $$`fee` is declared, but has it been assigned yet at the point it is used?$$ from new_challenge
union all
select id, 3, $$Move `const fee = 5;` above the line that uses it.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Every tracker shares one counter$$,
    $$javascript$$,
    $$scope_error$$,
    $$hard$$,
    $$trackTwice$$,
    $$const defaults = { count: 0 };

function makeTracker() {
    const state = defaults;
    return (n) => {
        state.count = state.count + n;
        return state.count;
    };
}

function trackTwice(a, b) {
    const first = makeTracker();
    first(a);
    const second = makeTracker();
    return second(b);
}$$,
    $$const defaults = { count: 0 };

function makeTracker() {
    const state = { ...defaults };
    return (n) => {
        state.count = state.count + n;
        return state.count;
    };
}

function trackTwice(a, b) {
    const first = makeTracker();
    first(a);
    const second = makeTracker();
    return second(b);
}$$,
    $$Each tracker from makeTracker() should start at zero, so trackTwice(5, 3) returns 3 — the second tracker's own total.$$,
    $$trackTwice(5, 3) returns 8 instead of 3. The second tracker somehow already knows about the first one's total.$$,
    $$`const state = defaults` does not copy anything — it binds a second name to the SAME object, so every tracker mutates one shared piece of state. const only prevents rebinding the name; the object it points at stays fully mutable. Spreading into a fresh object, { ...defaults }, gives each tracker its own. Note this is a shallow copy: nested objects would still be shared, which is the next version of this same bug.$$,
    $$[{"input":[5,3],"expected_output":3},{"input":[0,7],"expected_output":7},{"input":[100,1],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The second tracker's answer equals a + b. Where could it have learned about a?$$ from new_challenge
union all
select id, 2, $$Does `const state = defaults` create a new object, or another reference to the old one?$$ from new_challenge
union all
select id, 3, $$Copy it: const state = { ...defaults }.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Inner count shadows the one being returned$$,
    $$javascript$$,
    $$scope_error$$,
    $$medium$$,
    $$countMatches$$,
    $$function countMatches(words, target) {
    let count = 0;
    words.forEach(function (word) {
        let count = 0;
        if (word === target) {
            count = count + 1;
        }
    });
    return count;
}$$,
    $$function countMatches(words, target) {
    let count = 0;
    words.forEach(function (word) {
        if (word === target) {
            count = count + 1;
        }
    });
    return count;
}$$,
    $$countMatches(words, target) should count how many times target appears, so countMatches(["a","b","a"], "a") returns 2.$$,
    $$countMatches(["a","b","a"], "a") returns 0 — nothing is ever counted, even though the matches clearly exist.$$,
    $$The callback declares its OWN `count`, which shadows the outer one. Every increment lands on the inner variable, which is recreated at zero on each iteration and then thrown away, while the outer count never moves. Because the names match, the code reads as if it works. A closure can already see and modify the outer variable — declaring it again is what breaks the link. If you mean to use an outer variable, do not redeclare it.$$,
    $$[{"input":[["a","b","a"],"a"],"expected_output":2},{"input":[["x"],"y"],"expected_output":0},{"input":[["z","z","z"],"z"],"expected_output":3}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The matches happen — add a log inside the if to confirm. So why is the total zero?$$ from new_challenge
union all
select id, 2, $$There are two variables called count. Which one does the increment touch?$$ from new_challenge
union all
select id, 3, $$Remove the inner `let count = 0;` so the callback updates the outer one.$$ from new_challenge;
