-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 1 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Concurrent tally loses most of the votes$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$tallyVotes$$,
    $$const tick = () => new Promise((r) => setTimeout(r, 5));

async function tallyVotes(votes) {
    let total = 0;
    await Promise.all(
        votes.map(async (v) => {
            const current = total;
            await tick();
            total = current + v;
        })
    );
    return total;
}$$,
    $$const tick = () => new Promise((r) => setTimeout(r, 5));

async function tallyVotes(votes) {
    let total = 0;
    for (const v of votes) {
        await tick();
        total = total + v;
    }
    return total;
}$$,
    $$tallyVotes(votes) should add up every vote, so tallyVotes([1, 2, 3, 4]) returns 10.$$,
    $$tallyVotes([1, 2, 3, 4]) returns 4 instead of 10. Only the last vote seems to survive.$$,
    $$This is a lost-update race. Every callback reads `total` into `current` BEFORE awaiting, then all of them resume and write back `current + v`. Since they all read 0, each write overwrites the last, and only the final one survives. The read and the write are separated by an await, and anything can happen in that gap. The fix is to make the read-modify-write happen without yielding in between — either await first and then touch `total`, or process sequentially as the correct version does. Promise.all is not the villain here; interleaved access to shared mutable state is.$$,
    $$[{"input":[[1,2,3,4]],"expected_output":10},{"input":[[5,5]],"expected_output":10},{"input":[[7]],"expected_output":7}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Add a log inside the callback showing `current` each time. What value does every callback see?$$ from new_challenge
union all
select id, 2, $$Look at what happens between reading `total` and writing it back.$$ from new_challenge
union all
select id, 3, $$Each callback reads total before awaiting, so they all read 0. Don't hold a stale copy across an await.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Only the fastest request comes back$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$loadAll$$,
    $$const load = (id) =>
    new Promise((r) => setTimeout(() => r(id * 10), id));

async function loadAll(ids) {
    return await Promise.race(ids.map(load));
}$$,
    $$const load = (id) =>
    new Promise((r) => setTimeout(() => r(id * 10), id));

async function loadAll(ids) {
    return await Promise.all(ids.map(load));
}$$,
    $$loadAll(ids) should load every id and return all the results as an array, so loadAll([1, 2, 3]) returns [10, 20, 30].$$,
    $$loadAll([1, 2, 3]) returns 10 — a single number rather than an array of three results.$$,
    $$Promise.race settles as soon as the FIRST promise settles and gives you that one value; the rest keep running but their results are thrown away. Promise.all waits for every promise and resolves to an array of results in the original order. The names are easy to mix up because both take an array — remember that race is for 'whichever finishes first wins' (timeouts, fallbacks) and all is for 'I need all of these'.$$,
    $$[{"input":[[1,2,3]],"expected_output":[10,20,30]},{"input":[[2]],"expected_output":[20]},{"input":[[3,1]],"expected_output":[30,10]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The return value is a single number, not an array. What kind of thing returns just one result?$$ from new_challenge
union all
select id, 2, $$Compare what Promise.race resolves to against what Promise.all resolves to.$$ from new_challenge
union all
select id, 3, $$Promise.race resolves with the first settled value. You want Promise.all.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$try/catch never catches the async failure$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$safeDivide$$,
    $$const divide = async (a, b) => {
    if (b === 0) throw new Error("divide by zero");
    return a / b;
};

async function safeDivide(a, b) {
    try {
        return divide(a, b);
    } catch (err) {
        return -1;
    }
}$$,
    $$const divide = async (a, b) => {
    if (b === 0) throw new Error("divide by zero");
    return a / b;
};

async function safeDivide(a, b) {
    try {
        return await divide(a, b);
    } catch (err) {
        return -1;
    }
}$$,
    $$safeDivide(a, b) should return a / b, or -1 when the division fails. safeDivide(10, 0) should return -1.$$,
    $$safeDivide(10, 0) throws 'divide by zero' instead of returning -1, even though the call is wrapped in try/catch.$$,
    $$`return somePromise` inside a try block hands the promise back before it settles, so the try block has already exited by the time the rejection happens — there is nothing left on the stack to catch it. try/catch only catches synchronous throws and awaited rejections. Adding `await` keeps the function suspended inside the try block until the promise settles, so a rejection becomes a real throw the catch can see. This is the one place where the often-flagged 'redundant' `return await` is genuinely necessary.$$,
    $$[{"input":[10,2],"expected_output":5},{"input":[10,0],"expected_output":-1},{"input":[9,3],"expected_output":3}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The catch block never runs. When does a try block stop being 'active'?$$ from new_challenge
union all
select id, 2, $$The function returns the promise rather than its resolved value.$$ from new_challenge
union all
select id, 3, $$return await divide(a, b) — without await, the try block exits before the promise rejects.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Async reduce builds a string of Promises$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$sumAsync$$,
    $$const fetchValue = async (n) => n;

async function sumAsync(nums) {
    return nums.reduce(async (acc, n) => acc + (await fetchValue(n)), 0);
}$$,
    $$const fetchValue = async (n) => n;

async function sumAsync(nums) {
    return nums.reduce(
        async (acc, n) => (await acc) + (await fetchValue(n)),
        Promise.resolve(0)
    );
}$$,
    $$sumAsync(nums) should add up values fetched asynchronously, so sumAsync([1, 2, 3]) returns 6.$$,
    $$sumAsync([1, 2, 3]) returns the string "[object Promise]3" instead of 6.$$,
    $$An async callback always returns a promise, so on the second iteration `acc` is not a number — it is the promise returned by the previous iteration. Adding a promise to a number coerces it via toString, giving '[object Promise]'. The accumulator has to be awaited too: `(await acc) + ...`. Seeding with Promise.resolve(0) keeps the type consistent from the first iteration. If you find yourself writing this, a plain for...of loop is usually clearer — async reduce is a well-known readability trap.$$,
    $$[{"input":[[1,2,3]],"expected_output":6},{"input":[[10]],"expected_output":10},{"input":[[4,6]],"expected_output":10}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The result is a string. What turned a number into text?$$ from new_challenge
union all
select id, 2, $$What type is `acc` on the second iteration of an async reduce callback?$$ from new_challenge
union all
select id, 3, $$acc is a Promise, not a number. You need (await acc) + (await fetchValue(n)).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Results arrive in whatever order they finish$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$labelAll$$,
    $$const delay = (ms) => new Promise((r) => setTimeout(r, ms));

async function labelAll(items) {
    const out = [];
    await Promise.all(
        items.map(async (item) => {
            await delay(item.ms);
            out.push(item.name);
        })
    );
    return out;
}$$,
    $$const delay = (ms) => new Promise((r) => setTimeout(r, ms));

async function labelAll(items) {
    const out = [];
    await Promise.all(
        items.map(async (item, index) => {
            await delay(item.ms);
            out[index] = item.name;
        })
    );
    return out;
}$$,
    $$labelAll(items) should return the names in the same order they were passed in, regardless of how long each one takes.$$,
    $$labelAll([{name:"a",ms:20},{name:"b",ms:1}]) returns ["b","a"] — the order is wrong whenever a later item finishes first.$$,
    $$push() appends in COMPLETION order, and with concurrent work completion order has nothing to do with input order — the fastest item lands first. Promise.all preserves order in the array it resolves to, but this code ignores that and builds its own array by side effect. Writing to out[index] pins each result to its original slot, so timing no longer affects the output. The general rule: when order matters, index into a slot rather than appending, or just use the array Promise.all already gives you.$$,
    $$[{"input":[[{"name":"a","ms":20},{"name":"b","ms":1}]],"expected_output":["a","b"]},{"input":[[{"name":"x","ms":15},{"name":"y","ms":10},{"name":"z","ms":1}]],"expected_output":["x","y","z"]},{"input":[[{"name":"solo","ms":1}]],"expected_output":["solo"]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which item finishes first? Compare that against where it lands in the output.$$ from new_challenge
union all
select id, 2, $$push() appends whenever the callback happens to finish.$$ from new_challenge
union all
select id, 3, $$Use the map index to write into a fixed slot: out[index] = item.name.$$ from new_challenge;
