-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Second batch, part 4 of 5 (6 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$forEach finishes before the work does$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$doubleAll$$,
    $$function fetchDouble(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n * 2), 5));
}

async function doubleAll(nums) {
    const results = [];
    nums.forEach(async (n) => {
        results.push(await fetchDouble(n));
    });
    return results;
}$$,
    $$function fetchDouble(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n * 2), 5));
}

async function doubleAll(nums) {
    const results = [];
    for (const n of nums) {
        results.push(await fetchDouble(n));
    }
    return results;
}$$,
    $$doubleAll(nums) should resolve to a list with every number doubled.$$,
    $$doubleAll([1, 2, 3]) resolves to an empty array instead of [2, 4, 6].$$,
    $$forEach ignores the promise its callback returns, so it fires all three callbacks and moves on immediately — the function returns while every await is still pending. Array.forEach is simply not async-aware. Use a for...of loop with await inside, or Promise.all with map when the work can run in parallel.$$,
    $$[{"input":[[1,2,3]],"expected_output":[2,4,6]},{"input":[[5]],"expected_output":[10]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The results array is empty, not wrong — so the pushes hadn't happened yet when it was returned.$$ from new_challenge
union all
select id, 2, $$Does forEach wait for an async callback to finish before moving on?$$ from new_challenge
union all
select id, 3, $$forEach ignores returned promises. Use a for...of loop with await, or Promise.all(nums.map(...)).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Missing await turns the total into text$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$sumDelayed$$,
    $$function delay(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n), 1));
}

async function sumDelayed(nums) {
    let total = 0;
    for (const n of nums) {
        total += delay(n);
    }
    return total;
}$$,
    $$function delay(n) {
    return new Promise((resolve) => setTimeout(() => resolve(n), 1));
}

async function sumDelayed(nums) {
    let total = 0;
    for (const n of nums) {
        total += await delay(n);
    }
    return total;
}$$,
    $$sumDelayed(nums) should add up numbers that each arrive asynchronously, resolving to the total.$$,
    $$sumDelayed([1, 2, 3]) resolves to "0[object Promise][object Promise][object Promise]" instead of 6.$$,
    $$delay() returns a Promise, and without await you add the Promise object itself rather than its resolved value. JavaScript coerces it to the string "[object Promise]", so the total silently becomes text instead of throwing. A result containing "[object Promise]" is almost always a missing await.$$,
    $$[{"input":[[1,2,3]],"expected_output":6},{"input":[[10]],"expected_output":10},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Look at the exact text in the result — what type is being added to the total?$$ from new_challenge
union all
select id, 2, $$delay() hands back a Promise, not a number.$$ from new_challenge
union all
select id, 3, $$Add await before delay(n) so the resolved value is what gets added.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$map returns promises instead of values$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$wordLengths$$,
    $$async function wordLengths(words) {
    return words.map(async (word) => word.length);
}$$,
    $$async function wordLengths(words) {
    return Promise.all(words.map(async (word) => word.length));
}$$,
    $$wordLengths(words) should resolve to a list of each word's length.$$,
    $$wordLengths(["abc", "defg"]) resolves to [{}, {}] instead of [3, 4].$$,
    $$An async callback always returns a Promise, so map produces an array *of Promises*, and awaiting the outer function only unwraps one layer — not the promises inside the array. Promise.all turns an array of promises into a promise of an array, which is what you actually want.$$,
    $$[{"input":[["abc","defg"]],"expected_output":[3,4]},{"input":[["hi"]],"expected_output":[2]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The array has the right number of entries but the wrong contents. What are those entries?$$ from new_challenge
union all
select id, 2, $$An async function always returns a Promise — even a one-line one inside map.$$ from new_challenge
union all
select id, 3, $$Wrap the mapped array in Promise.all() so every inner promise resolves.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Copying settings changes the original$$,
    $$python$$,
    $$other$$,
    $$hard$$,
    $$with_theme$$,
    $$def with_theme(settings, theme):
    updated = settings.copy()
    updated["display"]["theme"] = theme
    return updated["display"]["theme"] + "|" + settings["display"]["theme"]$$,
    $$import copy

def with_theme(settings, theme):
    updated = copy.deepcopy(settings)
    updated["display"]["theme"] = theme
    return updated["display"]["theme"] + "|" + settings["display"]["theme"]$$,
    $$with_theme(settings, theme) should return a copy with a new theme, leaving the original untouched. It returns "newtheme|originaltheme" so you can see both.$$,
    $$Both halves come back the same — "dark|dark" — showing the original was modified too.$$,
    $$dict.copy() is a shallow copy: the new dict has its own top level, but the nested dicts are the *same objects* as the original's. Mutating settings['display'] therefore changes both. copy.deepcopy() recursively copies the nested structures. Shallow-copy bugs are nasty because the code looks defensive and passes any test using flat data.$$,
    $$[{"input":[{"display":{"theme":"light"}},"dark"],"expected_output":"dark|light"},{"input":[{"display":{"theme":"blue"}},"red"],"expected_output":"red|blue"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The original was supposed to stay unchanged. Check whether .copy() protects nested values.$$ from new_challenge
union all
select id, 2, $$copy() duplicates the outer dict only — the inner dict is shared between both.$$ from new_challenge
union all
select id, 3, $$Use copy.deepcopy(settings) so nested dictionaries are copied too.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Removing items skips every other one$$,
    $$python$$,
    $$other$$,
    $$hard$$,
    $$remove_evens$$,
    $$def remove_evens(nums):
    for n in nums:
        if n % 2 == 0:
            nums.remove(n)
    return nums$$,
    $$def remove_evens(nums):
    return [n for n in nums if n % 2 != 0]$$,
    $$remove_evens(nums) should return the list with all even numbers removed.$$,
    $$remove_evens([2, 4, 6, 1]) returns [4, 1] — one of the even numbers survives.$$,
    $$Removing from a list while iterating over it shifts every later element down one position, but the loop's internal index still advances — so the element that slid into the removed slot is skipped entirely. Never mutate a collection you're iterating. Build a new list instead, which a comprehension does cleanly.$$,
    $$[{"input":[[2,4,6,1]],"expected_output":[1]},{"input":[[1,3]],"expected_output":[1,3]},{"input":[[2,2]],"expected_output":[]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which even number survives, and where was it sitting relative to the one removed before it?$$ from new_challenge
union all
select id, 2, $$The list is being changed while the loop is walking through it.$$ from new_challenge
union all
select id, 3, $$Build a new list with a comprehension instead of removing from the one you're iterating.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Money totals gain a fraction of a cent$$,
    $$javascript$$,
    $$other$$,
    $$medium$$,
    $$addPrices$$,
    $$function addPrices(a, b) {
    return a + b;
}$$,
    $$function addPrices(a, b) {
    return Math.round((a + b) * 100) / 100;
}$$,
    $$addPrices(a, b) should add two prices in dollars and return a value correct to the cent.$$,
    $$addPrices(0.1, 0.2) returns 0.30000000000000004 instead of 0.3.$$,
    $$Floating-point numbers can't represent 0.1 or 0.2 exactly in binary, so the sum lands a hair off. This isn't a JavaScript quirk — it's how IEEE-754 works in nearly every language. For money, either round to the required precision after arithmetic, or work in integer cents and divide only when displaying.$$,
    $$[{"input":[0.1,0.2],"expected_output":0.3},{"input":[1.005,2.005],"expected_output":3.01},{"input":[5,5],"expected_output":10}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Look at the exact digits in the result — how far off is it, really?$$ from new_challenge
union all
select id, 2, $$This is about how computers store decimal fractions in binary.$$ from new_challenge
union all
select id, 3, $$Round after the arithmetic: Math.round((a + b) * 100) / 100.$$ from new_challenge;
