-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 9 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$next() explodes when nothing matches$$,
    $$python$$,
    $$null_or_undefined$$,
    $$hard$$,
    $$first_match$$,
    $$def first_match(items, target):
    return next(i for i in items if i == target)$$,
    $$def first_match(items, target):
    return next((i for i in items if i == target), -1)$$,
    $$first_match(items, target) should return the first matching item, or -1 when there is no match.$$,
    $$first_match([1, 2, 3], 5) raises StopIteration instead of returning -1.$$,
    $$next() raises StopIteration when the generator is exhausted — that is how iteration signals 'nothing left', and here it means 'no match'. Passing a second argument gives next() a default to return instead, which turns the exception into an ordinary value. Note the extra parentheses in the fix: with two arguments, the generator expression must be parenthesised or Python cannot tell where the first argument ends. StopIteration escaping into normal code is especially confusing because inside a for loop it is invisible — the loop consumes it.$$,
    $$[{"input":[[1,2,3],2],"expected_output":2},{"input":[[1,2,3],5],"expected_output":-1},{"input":[[],1],"expected_output":-1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What does next() do when the generator produces nothing?$$ from new_challenge
union all
select id, 2, $$next() accepts a second argument. What is it for?$$ from new_challenge
union all
select id, 3, $$next((...), -1) returns the default instead of raising StopIteration.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Missing score turns the total into a crash$$,
    $$python$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$total_score$$,
    $$def total_score(scores, names):
    return sum(scores.get(n) for n in names)$$,
    $$def total_score(scores, names):
    return sum(scores.get(n, 0) for n in names)$$,
    $$total_score(scores, names) should add up the scores for the named players, treating anyone without a score as 0.$$,
    $$total_score({'a': 5}, ['a', 'b']) raises TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'.$$,
    $$.get() returns None for a missing key — that is its whole point, as opposed to [] which raises KeyError. But None is not a number, so it blows up as soon as it reaches the addition. Supplying a second argument, .get(n, 0), gives a fallback of the right TYPE. The error surfaces at the sum rather than at the lookup, which is what makes this hard to trace: the line that crashes is not the line that is wrong. That gap between where a None is created and where it is finally used is the defining feature of null bugs.$$,
    $$[{"input":[{"a":5},["a","b"]],"expected_output":5},{"input":[{"a":5,"b":3},["a","b"]],"expected_output":8},{"input":[{},["x"]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The error mentions NoneType. Where could a None have come from?$$ from new_challenge
union all
select id, 2, $$What does dict.get() return for a key that is not there?$$ from new_challenge
union all
select id, 3, $$Give .get a default of the right type: scores.get(n, 0).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$A reading of zero counts as no reading$$,
    $$python$$,
    $$null_or_undefined$$,
    $$hard$$,
    $$describe_temp$$,
    $$def describe_temp(readings, station):
    reading = readings.get(station)
    if reading:
        return "recorded"
    return "missing"$$,
    $$def describe_temp(readings, station):
    reading = readings.get(station)
    if reading is not None:
        return "recorded"
    return "missing"$$,
    $$describe_temp(readings, station) should report 'recorded' whenever that station reported a temperature — including a reading of 0 degrees — and 'missing' only when the station is absent.$$,
    $$describe_temp({'north': 0}, 'north') returns 'missing' instead of 'recorded'. A genuine zero-degree reading is reported as no reading at all.$$,
    $$`if reading:` tests truthiness, not existence, and 0 is falsy — so a perfectly valid measurement is discarded. dict.get() returns None for a missing key, which is also falsy, and that is exactly why the two cases become indistinguishable. `is not None` asks the real question. This is most dangerous where zero is meaningful: temperatures, balances, counts, coordinates. A good habit — whenever a value might legitimately be 0, "" or an empty list, write the None check explicitly rather than leaning on truthiness.$$,
    $$[{"input":[{"north":0},"north"],"expected_output":"recorded"},{"input":[{"north":12},"north"],"expected_output":"recorded"},{"input":[{"north":3},"south"],"expected_output":"missing"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$A reading of 12 works, 0 does not. Is 0 truthy in Python?$$ from new_challenge
union all
select id, 2, $$The check is asking 'is this truthy', not 'does this exist'.$$ from new_challenge
union all
select id, 3, $$Use `if reading is not None:` so a zero reading still counts.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Page 1 shows the second page of results$$,
    $$javascript$$,
    $$off_by_one$$,
    $$hard$$,
    $$pageItems$$,
    $$function pageItems(items, page, size) {
    return items.slice(page * size, page * size + size);
}$$,
    $$function pageItems(items, page, size) {
    const start = (page - 1) * size;
    return items.slice(start, start + size);
}$$,
    $$pageItems(items, page, size) returns one page of results. Pages are numbered from 1, so pageItems([1,2,3,4,5,6], 1, 3) gives [1,2,3].$$,
    $$pageItems([1,2,3,4,5,6], 1, 3) returns [4,5,6] — page 1 shows page 2's contents, and the first three items are unreachable.$$,
    $$The formula page * size assumes pages are numbered from 0, but the API numbers them from 1 — so every page is shifted by one full page and the first page can never be reached. Converting at the boundary with (page - 1) * size keeps the 1-based public interface while doing 0-based arithmetic internally. Mixing 1-based and 0-based counting in the same expression is one of the most common sources of off-by-one bugs; decide which convention each layer uses and convert deliberately at the edge.$$,
    $$[{"input":[[1,2,3,4,5,6],1,3],"expected_output":[1,2,3]},{"input":[[1,2,3,4,5,6],2,3],"expected_output":[4,5,6]},{"input":[[1,2,3],1,2],"expected_output":[1,2]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Work out by hand what start index page 1 should use.$$ from new_challenge
union all
select id, 2, $$Are pages numbered from 0 or from 1? Does the formula agree?$$ from new_challenge
union all
select id, 3, $$Pages start at 1, so the offset is (page - 1) * size.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Loop runs one step past the end$$,
    $$javascript$$,
    $$off_by_one$$,
    $$easy$$,
    $$sumAll$$,
    $$function sumAll(nums) {
    let total = 0;
    for (let i = 0; i <= nums.length; i++) {
        total = total + nums[i];
    }
    return total;
}$$,
    $$function sumAll(nums) {
    let total = 0;
    for (let i = 0; i < nums.length; i++) {
        total = total + nums[i];
    }
    return total;
}$$,
    $$sumAll(nums) should add up every number in the array, so sumAll([1, 2, 3]) returns 6.$$,
    $$sumAll([1, 2, 3]) returns NaN instead of 6.$$,
    $$Array indices run from 0 to length - 1, so `i <= nums.length` takes one extra step and reads nums[3] on a three-element array. That is undefined, and 6 + undefined is NaN — which then poisons the rest of the sum. JavaScript does not throw for an out-of-range index, it just hands back undefined, so the mistake surfaces later and somewhere else. NaN appearing from nowhere in a numeric loop is a strong hint to check the bounds.$$,
    $$[{"input":[[1,2,3]],"expected_output":6},{"input":[[5]],"expected_output":5},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What is the last valid index of a 3-element array?$$ from new_challenge
union all
select id, 2, $$Log nums[i] each iteration and watch the final one.$$ from new_challenge
union all
select id, 3, $$`i <= nums.length` reads one past the end. Use `<`.$$ from new_challenge;
