-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 10 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Joined string ends with a stray dash$$,
    $$javascript$$,
    $$off_by_one$$,
    $$medium$$,
    $$joinWithDash$$,
    $$function joinWithDash(words) {
    let out = "";
    for (let i = 0; i < words.length; i++) {
        out = out + words[i] + "-";
    }
    return out;
}$$,
    $$function joinWithDash(words) {
    let out = "";
    for (let i = 0; i < words.length; i++) {
        if (i > 0) {
            out = out + "-";
        }
        out = out + words[i];
    }
    return out;
}$$,
    $$joinWithDash(words) should join words with dashes between them, so joinWithDash(["a","b"]) returns "a-b".$$,
    $$joinWithDash(["a","b"]) returns "a-b-" — there is a trailing dash.$$,
    $$This is the fencepost problem: n items need only n - 1 separators, but the loop adds one separator per item. Adding the dash BEFORE each item except the first gets the count right, and it handles the empty array correctly too. The name comes from fencing — a 10-metre fence with posts every metre needs 11 posts, not 10. Whenever you are alternating between items and separators, count them separately and check the difference.$$,
    $$[{"input":[["a","b"]],"expected_output":"a-b"},{"input":[["solo"]],"expected_output":"solo"},{"input":[["x","y","z"]],"expected_output":"x-y-z"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Count the words and count the dashes. How do the totals compare?$$ from new_challenge
union all
select id, 2, $$How many separators do 3 items actually need?$$ from new_challenge
union all
select id, 3, $$n items need n-1 separators. Add the dash before each item except the first.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Chunking silently drops the last group$$,
    $$python$$,
    $$off_by_one$$,
    $$hard$$,
    $$chunk$$,
    $$def chunk(items, size):
    out = []
    for i in range(0, len(items) - size, size):
        out.append(items[i:i + size])
    return out$$,
    $$def chunk(items, size):
    out = []
    for i in range(0, len(items), size):
        out.append(items[i:i + size])
    return out$$,
    $$chunk(items, size) should split a list into groups of size, keeping any short final group. chunk([1,2,3,4,5], 2) gives [[1,2],[3,4],[5]].$$,
    $$chunk([1,2,3,4,5], 2) returns [[1,2],[3,4]] — the final [5] is missing entirely.$$,
    $$Stopping at len(items) - size means the loop never starts a group that would run past the end, so any incomplete final chunk is skipped. But slicing in Python already clamps to the end of the list — items[4:6] on a 5-element list is simply [5], with no error — so the guard is unnecessary and actively harmful. Ranging over the full length lets the last partial group through. Losing trailing data is a particularly nasty bug because the output still looks well-formed.$$,
    $$[{"input":[[1,2,3,4,5],2],"expected_output":[[1,2],[3,4],[5]]},{"input":[[1,2,3,4],2],"expected_output":[[1,2],[3,4]]},{"input":[[1],3],"expected_output":[[1]]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$An even-sized list works. What is different when the size does not divide evenly?$$ from new_challenge
union all
select id, 2, $$What is the last value of i the range produces?$$ from new_challenge
union all
select id, 3, $$Slicing already stops safely at the end, so range over len(items), not len(items) - size.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Last character index is out of range$$,
    $$python$$,
    $$off_by_one$$,
    $$easy$$,
    $$last_char$$,
    $$def last_char(text):
    return text[len(text)]$$,
    $$def last_char(text):
    return text[len(text) - 1]$$,
    $$last_char(text) should return the final character, so last_char("hello") returns "o".$$,
    $$last_char("hello") raises IndexError: string index out of range.$$,
    $$Indices start at 0, so a 5-character string has indices 0 through 4 — index 5 does not exist. The last valid index is always len - 1. Python also offers text[-1], which counts from the end and is both shorter and harder to get wrong. Unlike JavaScript, Python raises IndexError rather than returning undefined, which is genuinely helpful: the failure appears exactly where the mistake is.$$,
    $$[{"input":["hello"],"expected_output":"o"},{"input":["a"],"expected_output":"a"},{"input":["debug"],"expected_output":"g"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Write out the indices of "hello" one by one.$$ from new_challenge
union all
select id, 2, $$If the length is 5, what is the highest valid index?$$ from new_challenge
union all
select id, 3, $$Use len(text) - 1, or simply text[-1].$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Sliding window never reaches the end$$,
    $$python$$,
    $$off_by_one$$,
    $$hard$$,
    $$max_window_sum$$,
    $$def max_window_sum(nums, k):
    best = 0
    for i in range(len(nums) - k):
        best = max(best, sum(nums[i:i + k]))
    return best$$,
    $$def max_window_sum(nums, k):
    best = 0
    for i in range(len(nums) - k + 1):
        best = max(best, sum(nums[i:i + k]))
    return best$$,
    $$max_window_sum(nums, k) should return the largest sum of any k consecutive numbers. max_window_sum([1,2,3,10], 2) is 13.$$,
    $$max_window_sum([1,2,3,10], 2) returns 5 instead of 13 — the window containing the largest value is never examined.$$,
    $$A list of length n has exactly n - k + 1 windows of size k, not n - k. Dropping the +1 means the final window — starting at index n - k — is never generated, so the answer is silently wrong rather than crashing. Check it on the smallest case: with n = k there is exactly 1 window, and n - k gives 0. Deriving the count from a tiny example is the fastest way to get these bounds right, and it catches the mistake before any test does.$$,
    $$[{"input":[[1,2,3,10],2],"expected_output":13},{"input":[[5,1,1],2],"expected_output":6},{"input":[[4,4],2],"expected_output":8}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$How many windows of size 2 fit in a list of 4 numbers? How many does the loop make?$$ from new_challenge
union all
select id, 2, $$Which window is missing from the ones being checked?$$ from new_challenge
union all
select id, 3, $$There are len(nums) - k + 1 windows. The range is missing the + 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Range check excludes its own lower bound$$,
    $$python$$,
    $$off_by_one$$,
    $$medium$$,
    $$count_in_range$$,
    $$def count_in_range(nums, low, high):
    return len([n for n in nums if low < n <= high])$$,
    $$def count_in_range(nums, low, high):
    return len([n for n in nums if low <= n <= high])$$,
    $$count_in_range(nums, low, high) counts values between low and high INCLUSIVE, so count_in_range([1,2,3], 1, 3) returns 3.$$,
    $$count_in_range([1,2,3], 1, 3) returns 2 instead of 3 — a value exactly equal to low is not counted, although one equal to high is.$$,
    $$The two comparisons are inconsistent: `<` excludes low while `<=` includes high, so the range is half-open when the specification calls for it to be closed. Boundary values are exactly the inputs least likely to be tested, which is how this survives. When a spec says 'inclusive', both ends need <=. It is worth writing one test per boundary — at low, at high, and just outside each — since that is where nearly all range bugs live.$$,
    $$[{"input":[[1,2,3],1,3],"expected_output":3},{"input":[[1,2,3],2,3],"expected_output":2},{"input":[[5],1,4],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which of the boundary values is being counted, and which is not?$$ from new_challenge
union all
select id, 2, $$Compare the two comparison operators in that condition.$$ from new_challenge
union all
select id, 3, $$'Inclusive' needs <= on both sides. Change low < n to low <= n.$$ from new_challenge;
