-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 8 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$A setting of zero falls back to the default$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$retriesFor$$,
    $$function retriesFor(settings) {
    return settings.retries || 3;
}$$,
    $$function retriesFor(settings) {
    return settings.retries ?? 3;
}$$,
    $$retriesFor(settings) should use settings.retries when it is provided and fall back to 3 when it is missing. Setting retries to 0 means 'do not retry'.$$,
    $$retriesFor({ retries: 0 }) returns 3 instead of 0 — turning retries off silently turns them back on.$$,
    $$|| falls back whenever the left side is FALSY, and 0 is falsy — along with "", false and NaN. So a legitimate zero is indistinguishable from a missing value. ?? (nullish coalescing) only falls back for null and undefined, which is what 'was this provided?' actually means. Use || when you genuinely want to replace any falsy value, and ?? when you mean 'unless it was not supplied'. This bug class is nasty precisely because it works for every value except the ones that mean 'off' or 'empty'.$$,
    $$[{"input":[{"retries":0}],"expected_output":0},{"input":[{"retries":5}],"expected_output":5},{"input":[{}],"expected_output":3}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It works for 5 but not for 0. What is special about 0?$$ from new_challenge
union all
select id, 2, $$List the values || treats as 'missing'.$$ from new_challenge
union all
select id, 3, $$0 is falsy, so || replaces it. Use ?? to fall back only on null/undefined.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$find() result used without checking$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$priceOf$$,
    $$function priceOf(items, name) {
    return items.find((item) => item.name === name).price;
}$$,
    $$function priceOf(items, name) {
    const found = items.find((item) => item.name === name);
    return found ? found.price : 0;
}$$,
    $$priceOf(items, name) should return the named item's price, or 0 when there is no such item.$$,
    $$priceOf([{name:"a",price:5}], "b") throws "Cannot read properties of undefined (reading 'price')" instead of returning 0.$$,
    $$Array.find returns undefined when nothing matches — it does not throw, and it does not return an empty object. Chaining .price straight onto the result assumes a match always exists, so the very first miss crashes. Any lookup that can fail needs its result checked before use. Note that find returning undefined is also why `find(...)?.price` gives undefined rather than 0 — if you need a specific fallback you still have to supply it.$$,
    $$[{"input":[[{"name":"a","price":5},{"name":"b","price":8}],"b"],"expected_output":8},{"input":[[{"name":"a","price":5}],"b"],"expected_output":0},{"input":[[],"x"],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What does find return when nothing matches?$$ from new_challenge
union all
select id, 2, $$The error says something is undefined — trace back to what produced it.$$ from new_challenge
union all
select id, 3, $$Store the result, check it, then read .price only if it exists.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Destructuring default ignores an explicit null$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$hard$$,
    $$greet$$,
    $$function greet(user) {
    const { name = "guest" } = user;
    return "hi " + name;
}$$,
    $$function greet(user) {
    const name = user.name ?? "guest";
    return "hi " + name;
}$$,
    $$greet(user) should greet the user by name, falling back to "guest" when no name is available.$$,
    $$greet({ name: null }) returns "hi null" instead of "hi guest", although greet({}) works fine.$$,
    $$Destructuring defaults are applied ONLY when the value is undefined. An explicit null is a real value, so the default is skipped and null flows straight into the string. The same rule governs default parameters: f(x = 1) uses 1 for undefined but not for null. This matters constantly with API and database data, where a missing field is usually null rather than undefined. When both need the same fallback, ?? is the tool — it treats null and undefined alike.$$,
    $$[{"input":[{"name":null}],"expected_output":"hi guest"},{"input":[{}],"expected_output":"hi guest"},{"input":[{"name":"vir"}],"expected_output":"hi vir"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The empty object works but an explicit null does not. What distinguishes them?$$ from new_challenge
union all
select id, 2, $$Exactly which value triggers a destructuring default?$$ from new_challenge
union all
select id, 3, $$Defaults only apply to undefined, never null. Use user.name ?? "guest".$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Optional chaining only guards the first link$$,
    $$javascript$$,
    $$null_or_undefined$$,
    $$hard$$,
    $$cityOf$$,
    $$function cityOf(user) {
    return user?.address.city ?? "unknown";
}$$,
    $$function cityOf(user) {
    return user?.address?.city ?? "unknown";
}$$,
    $$cityOf(user) should return the user's city, or "unknown" if any part of the path is missing.$$,
    $$cityOf(null) returns "unknown" as expected, but cityOf({}) throws "Cannot read properties of undefined (reading 'city')".$$,
    $$`?.` guards exactly the one access it is attached to — nothing further along the chain. user?.address safely yields undefined when user is null, but the very next `.city` is a plain access on that undefined and throws. Every link that can be missing needs its own ?. The reason it looks like it works is that a null user short-circuits the WHOLE expression, so the most obvious test case passes while the realistic one (an object that simply lacks the field) still crashes.$$,
    $$[{"input":[{}],"expected_output":"unknown"},{"input":[{"address":{"city":"pune"}}],"expected_output":"pune"},{"input":[null],"expected_output":"unknown"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$null works but {} does not. What is different about the second case?$$ from new_challenge
union all
select id, 2, $$How far along the chain does a single ?. actually protect you?$$ from new_challenge
union all
select id, 3, $$?. guards only its own access. You need user?.address?.city.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Zero retries becomes three retries$$,
    $$python$$,
    $$null_or_undefined$$,
    $$medium$$,
    $$retries_for$$,
    $$def retries_for(config):
    return config.get("retries") or 3$$,
    $$def retries_for(config):
    value = config.get("retries")
    if value is None:
        return 3
    return value$$,
    $$retries_for(config) should use config['retries'] when present and default to 3 when it is missing. A value of 0 means 'do not retry'.$$,
    $$retries_for({'retries': 0}) returns 3 instead of 0, so disabling retries has no effect.$$,
    $$`or` returns the right-hand side whenever the left is falsy, and in Python 0, "", [], {} and False are all falsy. So a deliberate 0 is treated exactly like a missing key. Testing `is None` asks the question you actually meant: was a value supplied at all? The `x = y or default` idiom is common and usually harmless, but it quietly breaks for every legitimate empty-or-zero value — which are often the most important cases.$$,
    $$[{"input":[{"retries":0}],"expected_output":0},{"input":[{"retries":5}],"expected_output":5},{"input":[{}],"expected_output":3}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$5 works, 0 does not. Which values does Python consider falsy?$$ from new_challenge
union all
select id, 2, $$`or` cannot tell 0 apart from a missing key.$$ from new_challenge
union all
select id, 3, $$Check `is None` explicitly instead of relying on truthiness.$$ from new_challenge;
