-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Second batch, part 5 of 5 (6 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Flatten only unwraps one level$$,
    $$javascript$$,
    $$other$$,
    $$medium$$,
    $$flattenDeep$$,
    $$function flattenDeep(arr) {
    return arr.flat();
}$$,
    $$function flattenDeep(arr) {
    return arr.flat(Infinity);
}$$,
    $$flattenDeep(arr) should flatten a nested array completely, however many levels deep it goes.$$,
    $$flattenDeep([1, [2, [3, [4]]]]) returns [1, 2, [3, [4]]] — still nested.$$,
    $$Array.flat() defaults to a depth of 1, so it removes exactly one level of nesting no matter how deep the structure is. Passing Infinity flattens all the way down. Defaults like this are easy to miss because the shallow case works perfectly, and the bug only appears once the data gets deeper.$$,
    $$[{"input":[[1,[2,[3,[4]]]]],"expected_output":[1,2,3,4]},{"input":[[1,[2]]],"expected_output":[1,2]},{"input":[[[[5]]]],"expected_output":[5]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It worked partially — exactly how many levels did it remove?$$ from new_challenge
union all
select id, 2, $$flat() takes an argument you're not passing.$$ from new_challenge
union all
select id, 3, $$flat() defaults to depth 1. Pass Infinity to flatten completely.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Uppercasing a string does nothing$$,
    $$python$$,
    $$other$$,
    $$easy$$,
    $$shout$$,
    $$def shout(text):
    text.upper()
    return text$$,
    $$def shout(text):
    return text.upper()$$,
    $$shout(text) should return the text in uppercase, so "hello" becomes "HELLO".$$,
    $$shout("hello") returns "hello" unchanged.$$,
    $$Strings are immutable in Python, so .upper() cannot modify text in place — it returns a new string, and here that return value is discarded. Any string method that looks like it 'does something' actually hands back a new string you have to keep. The same trap applies to .strip(), .replace() and friends.$$,
    $$[{"input":["hello"],"expected_output":"HELLO"},{"input":["Debug"],"expected_output":"DEBUG"},{"input":[""],"expected_output":""}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The call to upper() runs — so where does its result go?$$ from new_challenge
union all
select id, 2, $$Strings in Python cannot be changed in place.$$ from new_challenge
union all
select id, 3, $$upper() returns a new string. Return it directly instead of discarding it.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Capitalise repeats the first letter$$,
    $$javascript$$,
    $$off_by_one$$,
    $$easy$$,
    $$capitalize$$,
    $$function capitalize(word) {
    return word.charAt(0).toUpperCase() + word.slice(0);
}$$,
    $$function capitalize(word) {
    return word.charAt(0).toUpperCase() + word.slice(1);
}$$,
    $$capitalize(word) should upper-case the first letter, so "debug" becomes "Debug".$$,
    $$capitalize("debug") returns "Ddebug" — the first letter appears twice.$$,
    $$slice(0) returns the whole string, including the character that was already upper-cased and prepended. It needs to start from index 1 so the remainder excludes the first letter. An index of 0 where 1 was meant is one of the quietest off-by-one bugs, because the output looks almost right.$$,
    $$[{"input":["debug"],"expected_output":"Debug"},{"input":["a"],"expected_output":"A"},{"input":["hello world"],"expected_output":"Hello world"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Compare the output to the input letter by letter. What got duplicated?$$ from new_challenge
union all
select id, 2, $$The slice is returning more of the string than intended.$$ from new_challenge
union all
select id, 3, $$The first character is already handled, so the rest should start at index 1: slice(1).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Grouping keeps only the last match$$,
    $$javascript$$,
    $$logic_error$$,
    $$medium$$,
    $$groupByLength$$,
    $$function groupByLength(words) {
    const groups = {};
    for (const word of words) {
        groups[word.length] = [word];
    }
    return groups;
}$$,
    $$function groupByLength(words) {
    const groups = {};
    for (const word of words) {
        if (!groups[word.length]) {
            groups[word.length] = [];
        }
        groups[word.length].push(word);
    }
    return groups;
}$$,
    $$groupByLength(words) should group words by their length, so ["ab","cd","x"] gives {"1":["x"],"2":["ab","cd"]}.$$,
    $$Each group only ever holds one word — ["ab","cd"] gives {"2":["cd"]}, losing "ab".$$,
    $$Assigning a fresh single-item array replaces whatever was already stored under that key, so each group only keeps the last word seen. Grouping needs accumulation: create the array once if it's missing, then push onto it. The distinction between assigning and appending is what separates a grouping from a lookup.$$,
    $$[{"input":[["ab","cd","x"]],"expected_output":{"1":["x"],"2":["ab","cd"]}},{"input":[["a"]],"expected_output":{"1":["a"]}}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Each group holds exactly one word. Which one — the first or the last?$$ from new_challenge
union all
select id, 2, $$The assignment inside the loop overwrites whatever was there before.$$ from new_challenge
union all
select id, 3, $$Create the array only if it doesn't exist yet, then push onto it instead of assigning.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Word count breaks on double spaces$$,
    $$python$$,
    $$logic_error$$,
    $$easy$$,
    $$count_words$$,
    $$def count_words(text):
    return len(text.split(" "))$$,
    $$def count_words(text):
    return len(text.split())$$,
    $$count_words(text) should count the words in a string, however much whitespace separates them.$$,
    $$count_words("hello  world") returns 3 instead of 2 — the double space is counted as a word.$$,
    $$split(" ") splits on every single space, so consecutive spaces produce empty strings between them. Calling split() with no argument splits on any run of whitespace and discards the empties — which is almost always what you want for words. The two forms look interchangeable until the input has irregular spacing.$$,
    $$[{"input":["hello  world"],"expected_output":2},{"input":["one two three"],"expected_output":3},{"input":["single"],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try a string with two spaces in a row and print the list that split produces.$$ from new_challenge
union all
select id, 2, $$Splitting on a literal single space leaves empty strings behind.$$ from new_challenge
union all
select id, 3, $$Call split() with no arguments — it splits on any whitespace and drops the empties.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Merging settings mutates the defaults$$,
    $$python$$,
    $$other$$,
    $$medium$$,
    $$merge_settings$$,
    $$def merge_settings(defaults, overrides):
    defaults.update(overrides)
    return str(defaults.get("mode")) + "|" + str(len(defaults))$$,
    $$def merge_settings(defaults, overrides):
    merged = dict(defaults)
    merged.update(overrides)
    return str(merged.get("mode")) + "|" + str(len(defaults))$$,
    $$merge_settings(defaults, overrides) should merge overrides on top of defaults without changing the defaults. It returns "mode|numberOfDefaultKeys" so you can see both.$$,
    $$The key count reflects the merged result rather than the original defaults — merging a brand-new key into a one-key defaults dict reports 2 instead of 1.$$,
    $$dict.update() modifies the dictionary it's called on, in place. Since `defaults` was passed in by the caller, the caller's dictionary is changed too — a side effect the function name doesn't advertise. Copy first with dict(defaults), then update the copy. Functions that quietly mutate their arguments are a classic source of action-at-a-distance bugs.$$,
    $$[{"input":[{"mode":"light"},{"size":"big"}],"expected_output":"light|1"},{"input":[{"mode":"light"},{"mode":"dark","size":"big"}],"expected_output":"dark|1"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The merge itself is right — check whether the defaults you passed in survived unchanged.$$ from new_challenge
union all
select id, 2, $$update() works in place on the dictionary it is called on.$$ from new_challenge
union all
select id, 3, $$Copy first with dict(defaults), then update the copy and return that.$$ from new_challenge;
