-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 2 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Value returned from setTimeout goes nowhere$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$doubleLater$$,
    $$function doubleLater(value) {
    setTimeout(() => {
        return value * 2;
    }, 1);
}$$,
    $$function doubleLater(value) {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(value * 2);
        }, 1);
    });
}$$,
    $$doubleLater(value) should resolve to double the value after a short delay, so doubleLater(4) gives 8.$$,
    $$doubleLater(4) returns undefined instead of 8.$$,
    $$The return statement belongs to the arrow function passed to setTimeout, not to doubleLater. doubleLater itself falls off the end and returns undefined immediately — long before the timer even fires. A value produced later can only be handed back through a promise (or a callback). Wrapping the timer in `new Promise` and calling resolve gives the caller something to await. Returning from inside a callback and expecting it to escape the outer function is one of the most common early async mistakes.$$,
    $$[{"input":[4],"expected_output":8},{"input":[0],"expected_output":0},{"input":[-3],"expected_output":-6}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which function does that `return` actually belong to?$$ from new_challenge
union all
select id, 2, $$doubleLater finishes before the timer fires. What can it hand back in the meantime?$$ from new_challenge
union all
select id, 3, $$Wrap the setTimeout in new Promise and call resolve(value * 2) instead of returning.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Cache stampede loads the config twice$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$countLoads$$,
    $$async function countLoads(callCount) {
    let loads = 0;
    let cache = null;

    const getConfig = async () => {
        if (!cache) {
            loads = loads + 1;
            await new Promise((r) => setTimeout(r, 5));
            cache = { ready: true };
        }
        return cache;
    };

    const calls = [];
    for (let i = 0; i < callCount; i++) calls.push(getConfig());
    await Promise.all(calls);
    return loads;
}$$,
    $$async function countLoads(callCount) {
    let loads = 0;
    let cache = null;

    const getConfig = () => {
        if (!cache) {
            cache = (async () => {
                loads = loads + 1;
                await new Promise((r) => setTimeout(r, 5));
                return { ready: true };
            })();
        }
        return cache;
    };

    const calls = [];
    for (let i = 0; i < callCount; i++) calls.push(getConfig());
    await Promise.all(calls);
    return loads;
}$$,
    $$countLoads(n) makes n concurrent calls to a cached loader and returns how many times the expensive load actually ran. It should always be 1.$$,
    $$countLoads(3) returns 3 — the cache does nothing when the calls overlap, though countLoads(1) correctly returns 1.$$,
    $$The cache is only populated AFTER the await, so every caller that arrives during the in-flight load still sees `cache` as null and starts its own. This is a cache stampede, and it is invisible in sequential tests — it only appears under concurrency. The fix is to cache the PROMISE rather than the resolved value, and to do it synchronously before any await. Later callers then get the same in-flight promise and wait on the one load already running. The same pattern applies to any deduplicated async work: memoise the promise, not the result.$$,
    $$[{"input":[3],"expected_output":1},{"input":[1],"expected_output":1},{"input":[5],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Sequential calls work; concurrent ones don't. What is different about the timing?$$ from new_challenge
union all
select id, 2, $$When does `cache` actually get set, relative to the await?$$ from new_challenge
union all
select id, 3, $$Store the promise in the cache synchronously, before awaiting, so overlapping callers share it.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Missing await leaves a Promise in the array$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$medium$$,
    $$collectNames$$,
    $$const fetchName = async (id) => "user" + id;

async function collectNames(ids) {
    const names = ids.map((id) => fetchName(id));
    return names.length + "-" + typeof names[0];
}$$,
    $$const fetchName = async (id) => "user" + id;

async function collectNames(ids) {
    const names = await Promise.all(ids.map((id) => fetchName(id)));
    return names.length + "-" + typeof names[0];
}$$,
    $$collectNames(ids) should resolve every name and report the count and the type of the first entry, so collectNames([1,2]) gives "2-string".$$,
    $$collectNames([1, 2]) returns "2-object" instead of "2-string".$$,
    $$map with an async callback gives you an array of PROMISES, not an array of values — the length is right, which is exactly why this slips through, but every element is a pending promise (typeof 'object'). Awaiting the array itself does nothing either, since an array is not thenable. Promise.all converts the array of promises into a promise of an array, which is what you actually want. If you see 'object' where you expected a string, or [object Promise] in your output, this is almost always the cause.$$,
    $$[{"input":[[1,2]],"expected_output":"2-string"},{"input":[[7]],"expected_output":"1-string"},{"input":[[1,2,3]],"expected_output":"3-string"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The count is right but the type is wrong. What is actually sitting in the array?$$ from new_challenge
union all
select id, 2, $$An async callback returns a promise, even inside map.$$ from new_challenge
union all
select id, 3, $$Wrap the mapped array in await Promise.all(...).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Arrow body swallows the returned name$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$easy$$,
    $$getName$$,
    $$const loadUser = async (id) => ({ id: id, name: "user" + id });

function getName(id) {
    return loadUser(id).then((user) => {
        user.name;
    });
}$$,
    $$const loadUser = async (id) => ({ id: id, name: "user" + id });

function getName(id) {
    return loadUser(id).then((user) => {
        return user.name;
    });
}$$,
    $$getName(id) should resolve to the loaded user's name, so getName(1) gives "user1".$$,
    $$getName(1) resolves to undefined instead of the name.$$,
    $$An arrow function with a BLOCK body needs an explicit return; only the concise form (no braces) returns its expression automatically. Here the handler evaluates user.name and discards it, so the promise resolves with undefined. Because `.then` happily passes undefined along, nothing errors — the value just quietly disappears. Either add `return`, or drop the braces: `.then(user => user.name)`.$$,
    $$[{"input":[1],"expected_output":"user1"},{"input":[42],"expected_output":"user42"},{"input":[0],"expected_output":"user0"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Nothing throws, the value is simply missing. Where does it get lost?$$ from new_challenge
union all
select id, 2, $$Look closely at the arrow function's body — does it return anything?$$ from new_challenge
union all
select id, 3, $$An arrow with { } needs an explicit return. Add `return user.name;`.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Overbooking when everyone checks at once$$,
    $$javascript$$,
    $$async_race_condition$$,
    $$hard$$,
    $$bookSeats$$,
    $$async function bookSeats(requests) {
    let seatsLeft = 1;
    let booked = 0;

    const attempts = [];
    for (let i = 0; i < requests; i++) {
        attempts.push(
            (async () => {
                if (seatsLeft > 0) {
                    await new Promise((r) => setTimeout(r, 5));
                    seatsLeft = seatsLeft - 1;
                    booked = booked + 1;
                }
            })()
        );
    }
    await Promise.all(attempts);
    return booked;
}$$,
    $$async function bookSeats(requests) {
    let seatsLeft = 1;
    let booked = 0;

    const attempts = [];
    for (let i = 0; i < requests; i++) {
        attempts.push(
            (async () => {
                if (seatsLeft > 0) {
                    seatsLeft = seatsLeft - 1;
                    booked = booked + 1;
                    await new Promise((r) => setTimeout(r, 5));
                }
            })()
        );
    }
    await Promise.all(attempts);
    return booked;
}$$,
    $$bookSeats(n) handles n concurrent booking requests for a single remaining seat and returns how many bookings succeeded. It should never exceed 1.$$,
    $$bookSeats(3) returns 3 — three people booked the same single seat. bookSeats(1) correctly returns 1, so the bug only shows up under load.$$,
    $$This is a time-of-check to time-of-use (TOCTOU) race. Every request checks `seatsLeft > 0` and then awaits BEFORE decrementing, so all of them pass the check while the seat is still nominally available and only then start taking it. The check and the act must not be separated by a suspension point: decrementing before the await makes the seat unavailable to everyone who checks afterwards. This is the shape of real overbooking, double-spend and duplicate-signup bugs — and note that it is invisible to a single-user test, which is why concurrency needs its own test cases.$$,
    $$[{"input":[3],"expected_output":1},{"input":[1],"expected_output":1},{"input":[5],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$One request works fine; three do not. What do the three have in common?$$ from new_challenge
union all
select id, 2, $$Between checking seatsLeft and changing it, what else gets a chance to run?$$ from new_challenge
union all
select id, 3, $$Decrement seatsLeft before the await, so the check and the booking cannot be interleaved.$$ from new_challenge;
