-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 12 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Only the first dash gets removed$$,
    $$javascript$$,
    $$other$$,
    $$medium$$,
    $$stripDashes$$,
    $$function stripDashes(text) {
    return text.replace("-", "");
}$$,
    $$function stripDashes(text) {
    return text.replace(/-/g, "");
}$$,
    $$stripDashes(text) should remove every dash, so stripDashes("a-b-c") returns "abc".$$,
    $$stripDashes("a-b-c") returns "ab-c" — only the first dash is removed.$$,
    $$When replace() is given a STRING to search for, it replaces only the first occurrence. Replacing every match requires a regular expression with the global flag, /-/g. This trips people up because the single-replacement behaviour is easy to miss on short test input with only one match. Modern JavaScript also offers replaceAll(), which does what most people expect from the name — but note it throws if you hand it a non-global regex.$$,
    $$[{"input":["a-b-c"],"expected_output":"abc"},{"input":["no dashes"],"expected_output":"no dashes"},{"input":["-x-"],"expected_output":"x"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$How many dashes were removed, and how many were there?$$ from new_challenge
union all
select id, 2, $$What does replace() do when its first argument is a plain string?$$ from new_challenge
union all
select id, 3, $$Use a global regex: text.replace(/-/g, "") — or replaceAll.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Rounded values get glued together$$,
    $$javascript$$,
    $$other$$,
    $$hard$$,
    $$addRounded$$,
    $$function addRounded(a, b) {
    return a.toFixed(2) + b.toFixed(2);
}$$,
    $$function addRounded(a, b) {
    return Number((a + b).toFixed(2));
}$$,
    $$addRounded(a, b) should add two numbers and return the result rounded to two decimal places, as a number. addRounded(1, 2) is 3.$$,
    $$addRounded(1, 2) returns the string "1.002.00" instead of 3.$$,
    $$toFixed() returns a STRING, not a number, so + concatenates instead of adding. Two mistakes compound here: rounding was applied to each operand rather than to the result, and the string type was never converted back. Rounding intermediate values also loses precision that the final rounding would have preserved. The habit worth forming: round once, at the very end, and convert back with Number() if a number is what the caller expects.$$,
    $$[{"input":[1,2],"expected_output":3},{"input":[0.1,0.2],"expected_output":0.3},{"input":[1.5,1],"expected_output":2.5}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The output is a string. Which operation produced text?$$ from new_challenge
union all
select id, 2, $$Check what toFixed() actually returns.$$ from new_challenge
union all
select id, 3, $$toFixed gives a string, so + concatenates. Round the sum once and wrap it in Number().$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Sorting the names returns nothing$$,
    $$python$$,
    $$other$$,
    $$easy$$,
    $$sorted_names$$,
    $$def sorted_names(names):
    return names.sort()$$,
    $$def sorted_names(names):
    return sorted(names)$$,
    $$sorted_names(names) should return the names in alphabetical order, so sorted_names(["b","a"]) returns ["a","b"].$$,
    $$sorted_names(["b","a"]) returns None instead of the sorted list.$$,
    $$list.sort() sorts the list IN PLACE and returns None — that None return is deliberate, a convention marking methods that mutate rather than produce a new value. sorted() is the counterpart that leaves the input alone and returns a new sorted list. The same distinction applies to list.reverse() versus reversed(). If a function mysteriously returns None, check whether the last thing it called was a mutating method.$$,
    $$[{"input":[["b","a"]],"expected_output":["a","b"]},{"input":[["c","a","b"]],"expected_output":["a","b","c"]},{"input":[["only"]],"expected_output":["only"]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The function returns None. What was the last thing it evaluated?$$ from new_challenge
union all
select id, 2, $$Look up what list.sort() returns.$$ from new_challenge
union all
select id, 3, $$sort() sorts in place and returns None. Use sorted(names).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Copying a grid still shares its rows$$,
    $$python$$,
    $$other$$,
    $$hard$$,
    $$original_after_edit$$,
    $$def original_after_edit(grid):
    copy = grid[:]
    copy[0][0] = 99
    return grid[0][0]$$,
    $$def original_after_edit(grid):
    copy = [row[:] for row in grid]
    copy[0][0] = 99
    return grid[0][0]$$,
    $$The function copies a grid, edits the copy, then reports the ORIGINAL's first cell — which should be unchanged. For [[1,2],[3,4]] it returns 1.$$,
    $$original_after_edit([[1,2],[3,4]]) returns 99 — editing the copy changed the original too.$$,
    $$grid[:] makes a SHALLOW copy: a new outer list whose elements still point at the very same inner lists. Replacing a whole row in the copy would be safe, but reaching into a row mutates an object both grids share. Copying each row as well gives real independence. Beyond two levels, copy.deepcopy() handles arbitrary nesting. The rule to remember: a shallow copy protects only the top level, and the depth of your copy has to match the depth at which you mutate.$$,
    $$[{"input":[[[1,2],[3,4]]],"expected_output":1},{"input":[[[7]]],"expected_output":7},{"input":[[[5,0],[0,0]]],"expected_output":5}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The copy was edited, not the original. So why did the original change?$$ from new_challenge
union all
select id, 2, $$What exactly does grid[:] duplicate — the outer list, the inner ones, or both?$$ from new_challenge
union all
select id, 3, $$It is a shallow copy. Copy each row too: [row[:] for row in grid].$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Summing a dict adds up the keys$$,
    $$python$$,
    $$other$$,
    $$medium$$,
    $$total_values$$,
    $$def total_values(data):
    return sum(data)$$,
    $$def total_values(data):
    return sum(data.values())$$,
    $$total_values(data) should add up a dictionary's values, so total_values({'a': 1, 'b': 2}) returns 3.$$,
    $$total_values({'a': 1, 'b': 2}) raises TypeError: unsupported operand type(s) for +: 'int' and 'str'.$$,
    $$Iterating a dictionary yields its KEYS, not its values — so sum(data) tries to add the strings 'a' and 'b'. The error at least makes the problem visible here; with numeric keys it would have silently returned the sum of the wrong numbers, which is far worse. Use .values() for the values, .items() for both, and remember that the same rule governs `for k in data` and `if x in data`, which both work on keys.$$,
    $$[{"input":[{"a":1,"b":2}],"expected_output":3},{"input":[{"x":10}],"expected_output":10},{"input":[{}],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The error mentions a str. Where would a string have come from?$$ from new_challenge
union all
select id, 2, $$What do you get when you iterate over a dictionary directly?$$ from new_challenge
union all
select id, 3, $$Iterating a dict gives keys. Use sum(data.values()).$$ from new_challenge;
