-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 4 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Adding to a global total raises UnboundLocalError$$,
    $$python$$,
    $$scope_error$$,
    $$medium$$,
    $$add_all$$,
    $$total = 0

def add_all(nums):
    for n in nums:
        total += n
    return total$$,
    $$total = 0

def add_all(nums):
    running = 0
    for n in nums:
        running += n
    return running$$,
    $$add_all(nums) should return the sum of the numbers, so add_all([1, 2, 3]) returns 6.$$,
    $$add_all([1, 2, 3]) raises UnboundLocalError: cannot access local variable 'total' — even though total is defined at the top of the file.$$,
    $$Assigning to a name anywhere inside a function makes it local for the WHOLE function, so `total += n` is read-then-write on a local that has never been assigned. Python decides local-vs-global when it compiles the function, not while it runs, which is why the module-level total is invisible here. You could declare `global total`, but that leaves the function stateful — calling it twice would keep accumulating. Using a fresh local accumulator is almost always the better fix: the function then depends on nothing outside itself.$$,
    $$[{"input":[[1,2,3]],"expected_output":6},{"input":[[]],"expected_output":0},{"input":[[10,-4]],"expected_output":6}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$total is defined at module level, yet Python calls it local. What made it local?$$ from new_challenge
union all
select id, 2, $$`total += n` both reads and writes total. Which one fails?$$ from new_challenge
union all
select id, 3, $$Assigning to a name makes it local for the entire function. Use a new local accumulator instead.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$All the lambdas use the last factor$$,
    $$python$$,
    $$scope_error$$,
    $$hard$$,
    $$apply_first$$,
    $$def make_multipliers(factors):
    return [lambda x: x * f for f in factors]

def apply_first(factors, value):
    return make_multipliers(factors)[0](value)$$,
    $$def make_multipliers(factors):
    return [lambda x, f=f: x * f for f in factors]

def apply_first(factors, value):
    return make_multipliers(factors)[0](value)$$,
    $$make_multipliers([2, 3, 4]) should build one multiplier per factor, so the FIRST one doubles: apply_first([2, 3, 4], 10) returns 20.$$,
    $$apply_first([2, 3, 4], 10) returns 40 — the first multiplier is using 4, the last factor, instead of 2.$$,
    $$Closures in Python capture the VARIABLE, not its value at the time the lambda was created. Every lambda refers to the same `f`, and by the time any of them runs, the comprehension has finished and f holds the final factor. Binding it as a default argument, `lambda x, f=f:`, evaluates f immediately at definition time and freezes it per lambda. This is called late binding, and it bites hardest when building callbacks or handlers in a loop — the symptom is always 'they all behave like the last one'.$$,
    $$[{"input":[[2,3,4],10],"expected_output":20},{"input":[[5,1],3],"expected_output":15},{"input":[[7],2],"expected_output":14}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Every multiplier behaves identically. Which factor are they all using?$$ from new_challenge
union all
select id, 2, $$When the lambda finally runs, what does `f` refer to?$$ from new_challenge
union all
select id, 3, $$Capture the value at definition time with a default argument: lambda x, f=f: x * f.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Two baskets share the same list$$,
    $$python$$,
    $$scope_error$$,
    $$hard$$,
    $$two_baskets$$,
    $$class Basket:
    items = []

    def add(self, item):
        self.items.append(item)


def two_baskets(first, second):
    a = Basket()
    a.add(first)
    b = Basket()
    b.add(second)
    return len(b.items)$$,
    $$class Basket:
    def __init__(self):
        self.items = []

    def add(self, item):
        self.items.append(item)


def two_baskets(first, second):
    a = Basket()
    a.add(first)
    b = Basket()
    b.add(second)
    return len(b.items)$$,
    $$Each Basket should have its own items, so after adding one thing to a fresh basket, two_baskets('x', 'y') returns 1.$$,
    $$two_baskets('x', 'y') returns 2 — the second basket already contains the first basket's item.$$,
    $$`items = []` in the class body is a CLASS attribute, created once when the class is defined and shared by every instance. self.items.append() mutates that one shared list rather than a per-instance one. Assigning in __init__ gives each instance its own list. The trap is that this looks like a normal field declaration in most other languages. A useful tell: mutating a class attribute affects all instances, whereas rebinding one (self.items = [...]) silently creates an instance attribute and hides the bug in a different way.$$,
    $$[{"input":["x","y"],"expected_output":1},{"input":["a","b"],"expected_output":1},{"input":[1,2],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Print b.items. Where did the extra entry come from?$$ from new_challenge
union all
select id, 2, $$When is `items = []` evaluated — once, or once per Basket?$$ from new_challenge
union all
select id, 3, $$Move it into __init__ so each instance gets its own list.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Result variable never exists when nothing matches$$,
    $$python$$,
    $$scope_error$$,
    $$easy$$,
    $$last_even$$,
    $$def last_even(nums):
    for n in nums:
        if n % 2 == 0:
            found = n
    return found$$,
    $$def last_even(nums):
    found = -1
    for n in nums:
        if n % 2 == 0:
            found = n
    return found$$,
    $$last_even(nums) should return the last even number, or -1 if there are none. last_even([1, 3]) should return -1.$$,
    $$last_even([1, 3]) raises UnboundLocalError: cannot access local variable 'found'. It works fine when the list contains an even number.$$,
    $$`found` is only created if the if-branch runs at least once. When no element is even, the assignment never executes and the return line refers to a name that was never bound. Python has no concept of a declared-but-unset local — a variable exists only once something assigns to it. Initialising before the loop guarantees the name exists on every path and, just as importantly, makes the 'nothing found' answer explicit rather than accidental.$$,
    $$[{"input":[[1,2,3,4]],"expected_output":4},{"input":[[1,3]],"expected_output":-1},{"input":[[]],"expected_output":-1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It only breaks for some inputs. What is different about those?$$ from new_challenge
union all
select id, 2, $$Trace which lines run when no number is even.$$ from new_challenge
union all
select id, 3, $$Initialise found = -1 before the loop so it always exists.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$continue skips past the increment$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$medium$$,
    $$countOdds$$,
    $$function countOdds(nums) {
    let i = 0;
    let count = 0;
    while (i < nums.length) {
        if (nums[i] % 2 === 0) {
            continue;
        }
        count = count + 1;
        i = i + 1;
    }
    return count;
}$$,
    $$function countOdds(nums) {
    let i = 0;
    let count = 0;
    while (i < nums.length) {
        if (nums[i] % 2 !== 0) {
            count = count + 1;
        }
        i = i + 1;
    }
    return count;
}$$,
    $$countOdds(nums) should count the odd numbers, so countOdds([1, 2, 3]) returns 2.$$,
    $$countOdds([1, 3]) returns 2 correctly, but countOdds([1, 2, 3]) hangs the page forever.$$,
    $$`continue` jumps straight back to the loop condition, skipping every remaining statement in the body — including `i = i + 1`. So the moment an even number appears, i stops advancing and the loop re-tests the same element forever. This is the classic hazard of `continue` in a while loop: the increment lives in the body, so any early jump strands it. Either advance the index before continuing, or restructure so the increment always runs — a plain for loop puts the increment in the header where continue cannot skip it.$$,
    $$[{"input":[[1,2,3]],"expected_output":2},{"input":[[2,4]],"expected_output":0},{"input":[[1,3,5]],"expected_output":3}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$It only hangs for some inputs. What do those inputs contain?$$ from new_challenge
union all
select id, 2, $$Follow what `continue` skips over on an even number.$$ from new_challenge
union all
select id, 3, $$continue jumps past i = i + 1, so the index never moves. Make sure the increment always runs.$$ from new_challenge;
