-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 7 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Identical objects counted as different$$,
    $$javascript$$,
    $$type_error$$,
    $$hard$$,
    $$countUnique$$,
    $$function countUnique(records) {
    const seen = [];
    for (const record of records) {
        if (!seen.some((s) => s === record)) {
            seen.push(record);
        }
    }
    return seen.length;
}$$,
    $$function countUnique(records) {
    const seen = [];
    for (const record of records) {
        const key = JSON.stringify(record);
        if (!seen.some((s) => JSON.stringify(s) === key)) {
            seen.push(record);
        }
    }
    return seen.length;
}$$,
    $$countUnique(records) should count distinct records by their contents, so two records with the same fields count once.$$,
    $$countUnique([{id:1},{id:1}]) returns 2 instead of 1, even though the two objects look identical.$$,
    $$=== on objects compares REFERENCES, not contents — it asks 'are these the same object in memory', and two separately created objects are never equal no matter how identical they look. Primitives compare by value, which is why this catches people out: the same operator means something different depending on the type. To compare contents you need a value-based key; JSON.stringify works for simple flat data (though it is order-sensitive and cannot handle cycles). For anything richer, compare field by field or use a proper deep-equal.$$,
    $$[{"input":[[{"id":1},{"id":1}]],"expected_output":1},{"input":[[{"id":1},{"id":2}]],"expected_output":2},{"input":[[{"id":3}]],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The two objects have the same contents. Does === care about contents?$$ from new_challenge
union all
select id, 2, $$Try comparing two freshly created objects with === in a console.$$ from new_challenge
union all
select id, 3, $$=== compares object identity. Compare a value-based key such as JSON.stringify(record).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Numbers arriving as text never compare properly$$,
    $$python$$,
    $$type_error$$,
    $$medium$$,
    $$count_above$$,
    $$def count_above(values, threshold):
    return len([v for v in values if v > threshold])$$,
    $$def count_above(values, threshold):
    return len([v for v in values if int(v) > threshold])$$,
    $$count_above(values, threshold) counts how many values exceed the threshold. The values arrive as strings from a form, so count_above(["1", "5", "10"], 3) should return 2.$$,
    $$count_above(["1", "5", "10"], 3) raises TypeError: '>' not supported between instances of 'str' and 'int'.$$,
    $$Python 3 refuses to order values of unrelated types, so comparing a str to an int is an error rather than a guess. This is deliberate: Python 2 allowed it and produced meaningless results that silently corrupted data. Converting explicitly with int(v) makes the intent obvious. The real lesson is about boundaries — anything coming from a form, a CSV, a query string or JSON arrives as text, and converting it once at the edge is far better than scattering int() calls through your logic.$$,
    $$[{"input":[["1","5","10"],3],"expected_output":2},{"input":[["1","2"],5],"expected_output":0},{"input":[["7"],3],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Read the error carefully — which two types is it refusing to compare?$$ from new_challenge
union all
select id, 2, $$What type are the entries in `values`, really?$$ from new_challenge
union all
select id, 3, $$They are strings. Convert before comparing: int(v) > threshold.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Float division makes an invalid index$$,
    $$python$$,
    $$type_error$$,
    $$easy$$,
    $$middle_item$$,
    $$def middle_item(items):
    return items[len(items) / 2]$$,
    $$def middle_item(items):
    return items[len(items) // 2]$$,
    $$middle_item(items) should return the middle element, so middle_item([1, 2, 3]) returns 2.$$,
    $$middle_item([1, 2, 3]) raises TypeError: list indices must be integers or slices, not float.$$,
    $$In Python 3, `/` is true division and ALWAYS produces a float — 3 / 2 is 1.5, and even 4 / 2 is 2.0 rather than 2. A float can never be a list index, however round it looks. `//` is floor division and returns an int for int operands, which is what indexing needs. This changed from Python 2, where / on two ints did floor division, so older code and older tutorials get this wrong.$$,
    $$[{"input":[[1,2,3]],"expected_output":2},{"input":[["a","b","c"]],"expected_output":"b"},{"input":[[10,20,30,40,50]],"expected_output":30}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The error names a type. What type is len(items) / 2?$$ from new_challenge
union all
select id, 2, $$Try printing 4 / 2 in Python 3 and look at how it displays.$$ from new_challenge
union all
select id, 3, $$/ always returns a float. Use // for an integer index.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$JSON keys are strings, but the ids are numbers$$,
    $$python$$,
    $$type_error$$,
    $$hard$$,
    $$total_for_ids$$,
    $$def total_for_ids(counts, ids):
    return sum(counts[i] for i in ids)$$,
    $$def total_for_ids(counts, ids):
    return sum(counts[str(i)] for i in ids)$$,
    $$total_for_ids(counts, ids) totals the counts for the given ids. counts comes from a JSON payload, e.g. {"1": 10, "2": 20}, and ids are integers.$$,
    $$total_for_ids({"1": 10, "2": 20}, [1, 2]) raises KeyError: 1 — even though the key is plainly there in the dict.$$,
    $$JSON object keys are ALWAYS strings, so parsing {"1": 10} gives you the key "1", not 1. Python dicts distinguish them: "1" and 1 hash differently and are entirely separate keys. The KeyError is confusing because printing the dict shows quotes that are easy to skim past. Converting the lookup with str(i) fixes it here, but the more robust habit is to normalise keys once when the data comes in, so the rest of your code does not have to remember which side of the boundary it is on.$$,
    $$[{"input":[{"1":10,"2":20},[1,2]],"expected_output":30},{"input":[{"5":3},[5]],"expected_output":3},{"input":[{"1":1,"2":2,"3":3},[1,3]],"expected_output":4}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The KeyError says 1. Print list(counts.keys()) and look closely at what you get.$$ from new_challenge
union all
select id, 2, $$Is the key the integer 1, or the string "1"?$$ from new_challenge
union all
select id, 3, $$JSON keys are always strings. Look up counts[str(i)].$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Highest score picked alphabetically$$,
    $$python$$,
    $$type_error$$,
    $$medium$$,
    $$highest$$,
    $$def highest(values):
    return max(values)$$,
    $$def highest(values):
    return max(values, key=int)$$,
    $$highest(values) should return the largest number from a list of numeric strings, so highest(["9", "10", "2"]) returns "10".$$,
    $$highest(["9", "10", "2"]) returns "9" instead of "10".$$,
    $$Comparing strings compares them character by character, so "9" beats "10" because '9' comes after '1'. It is the same reason files sort as 1, 10, 2 in a file browser. max() is doing exactly what it was asked; the values are simply the wrong type for the comparison you meant. Passing key=int tells max how to rank them without changing what it returns. Converting the whole list to ints up front works too, and is better if you need the numbers afterwards.$$,
    $$[{"input":[["9","10","2"]],"expected_output":"10"},{"input":[["100","99"]],"expected_output":"100"},{"input":[["5"]],"expected_output":"5"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Compare "9" and "10" directly in Python. Which one is greater?$$ from new_challenge
union all
select id, 2, $$How does Python order two strings?$$ from new_challenge
union all
select id, 3, $$Strings compare character by character. Use max(values, key=int).$$ from new_challenge;
