-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Third batch, part 6 of 12 (5 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Retry flag compared instead of assigned$$,
    $$python$$,
    $$infinite_loop$$,
    $$easy$$,
    $$attempts_until_success$$,
    $$def attempts_until_success(succeed_on):
    tries = 0
    done = False
    while not done:
        tries += 1
        if tries == succeed_on:
            done == True
    return tries$$,
    $$def attempts_until_success(succeed_on):
    tries = 0
    done = False
    while not done:
        tries += 1
        if tries == succeed_on:
            done = True
    return tries$$,
    $$attempts_until_success(n) retries until the nth attempt succeeds and returns the number of tries, so attempts_until_success(3) returns 3.$$,
    $$attempts_until_success(3) never returns.$$,
    $$`done == True` is a comparison, not an assignment. It computes False, throws the answer away, and leaves `done` exactly as it was — so the loop condition never flips. Python allows a bare expression as a statement, which is why this is legal code rather than a syntax error. One character separates == from =, and the line reads almost identically. Some linters flag a statement with no effect; it is worth turning that warning on.$$,
    $$[{"input":[3],"expected_output":3},{"input":[1],"expected_output":1},{"input":[5],"expected_output":5}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The loop ends when `done` becomes True. Does it ever become True?$$ from new_challenge
union all
select id, 2, $$Look very carefully at the line that is supposed to set the flag.$$ from new_challenge
union all
select id, 3, $$`done == True` compares; you want `done = True` to assign.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Halving loop with no plan for odd numbers$$,
    $$python$$,
    $$infinite_loop$$,
    $$medium$$,
    $$shrink_to_one$$,
    $$def shrink_to_one(n):
    steps = 0
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        steps += 1
    return steps$$,
    $$def shrink_to_one(n):
    steps = 0
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        steps += 1
    return steps$$,
    $$shrink_to_one(n) applies the Collatz rule — halve even numbers, and turn odd n into 3n + 1 — counting steps until n reaches 1. shrink_to_one(6) returns 8.$$,
    $$shrink_to_one(8) returns 3, but shrink_to_one(6) hangs. Powers of two work; everything else freezes.$$,
    $$There is no else branch, so when n is odd nothing changes it — the loop keeps testing the same odd value forever. Powers of two halve cleanly all the way to 1 and never meet an odd number above 1, which is why they hide the bug entirely. Whenever a loop's progress depends on a condition, ask what happens when that condition is false: if the answer is 'nothing', the loop can stall. Choosing test inputs that exercise BOTH branches would have caught this immediately.$$,
    $$[{"input":[6],"expected_output":8},{"input":[8],"expected_output":3},{"input":[7],"expected_output":16}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Powers of two work; other numbers hang. What is special about powers of two here?$$ from new_challenge
union all
select id, 2, $$Trace what happens to n when it is odd.$$ from new_challenge
union all
select id, 3, $$The if has no else, so odd values never change. Add else: n = 3 * n + 1.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Loose equality counts empty strings as zero$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$countZeros$$,
    $$function countZeros(values) {
    return values.filter((v) => v == 0).length;
}$$,
    $$function countZeros(values) {
    return values.filter((v) => v === 0).length;
}$$,
    $$countZeros(values) should count how many entries are the number zero, so countZeros([0, "", false, 0]) returns 2.$$,
    $$countZeros([0, "", false, 0]) returns 4 — empty strings and false are being counted as zero.$$,
    $$== converts both sides to a common type before comparing, and "" , false and even [] all convert to 0. So the filter matches far more than intended. === compares type first and returns false immediately when the types differ, which is almost always what you actually mean. This is why the default advice is to use === everywhere; the one common exception is `x == null`, which conveniently matches both null and undefined.$$,
    $$[{"input":[[0,"",false,0]],"expected_output":2},{"input":[[1,2,3]],"expected_output":0},{"input":[[0,"0",0]],"expected_output":2}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which of "" and false does the filter currently accept?$$ from new_challenge
union all
select id, 2, $$Think about what == does before it compares.$$ from new_challenge
union all
select id, 3, $$== coerces types. Use === so type mismatches fail immediately.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$parseInt quietly throws away the decimals$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$sumPrices$$,
    $$function sumPrices(prices) {
    return prices.reduce((sum, p) => sum + parseInt(p), 0);
}$$,
    $$function sumPrices(prices) {
    return prices.reduce((sum, p) => sum + parseFloat(p), 0);
}$$,
    $$sumPrices(prices) should total a list of price strings, so sumPrices(["1.5", "2.5"]) returns 4.$$,
    $$sumPrices(["1.5", "2.5"]) returns 3 instead of 4 — every price loses its decimal part.$$,
    $$parseInt stops reading at the first character that cannot be part of an integer, so it takes '1.5', reads '1', hits the dot and stops — silently returning 1. It does not round and it does not complain. parseFloat (or Number) keeps the fractional part. The wider trap is that parseInt is lenient in both directions: parseInt('12abc') is 12, so it accepts input you might want rejected. Number('12abc') gives NaN, which is often the safer signal.$$,
    $$[{"input":[["1.5","2.5"]],"expected_output":4},{"input":[["10"]],"expected_output":10},{"input":[["0.25","0.25","0.5"]],"expected_output":1}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The total is always a bit low. How much is each price losing?$$ from new_challenge
union all
select id, 2, $$What does parseInt do when it reaches the decimal point?$$ from new_challenge
union all
select id, 3, $$parseInt truncates at the dot. Use parseFloat or Number.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$typeof reports null as an object$$,
    $$javascript$$,
    $$type_error$$,
    $$hard$$,
    $$describeType$$,
    $$function describeType(value) {
    if (typeof value === "object") {
        return "object";
    }
    return typeof value;
}$$,
    $$function describeType(value) {
    if (value === null) {
        return "null";
    }
    if (typeof value === "object") {
        return "object";
    }
    return typeof value;
}$$,
    $$describeType(value) should name the type of a value, returning "null" for null and "object" for real objects.$$,
    $$describeType(null) returns "object" instead of "null".$$,
    $$typeof null has returned 'object' since the first version of JavaScript. It is a long-standing bug in the language that cannot be fixed without breaking the web, so it is now permanent. That means typeof alone can never distinguish null from a real object — you have to check `value === null` explicitly, and check it FIRST. This is the root cause of countless 'cannot read property of null' crashes: a typeof guard that looked like it covered the case but did not.$$,
    $$[{"input":[null],"expected_output":"null"},{"input":[{"a":1}],"expected_output":"object"},{"input":[5],"expected_output":"number"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Run typeof null in a console. Does the answer surprise you?$$ from new_challenge
union all
select id, 2, $$The object branch is catching something it should not.$$ from new_challenge
union all
select id, 3, $$typeof null is 'object' — a famous language bug. Check value === null before the typeof test.$$ from new_challenge;
