-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Second batch, part 2 of 5 (6 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Leap year check gets century years wrong$$,
    $$python$$,
    $$logic_error$$,
    $$medium$$,
    $$is_leap_year$$,
    $$def is_leap_year(year):
    return year % 4 == 0 and year % 100 != 0$$,
    $$def is_leap_year(year):
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)$$,
    $$is_leap_year(year) should return True for leap years: divisible by 4, except centuries, unless divisible by 400.$$,
    $$is_leap_year(2000) returns False, even though 2000 was a leap year.$$,
    $$The rule has three parts and the code only implements two. Years divisible by 100 are excluded — correct for 1900 — but the exception to that exception is missing: years divisible by 400 are leap years after all. Whenever a spec says 'except… unless…', make sure every clause made it into the code.$$,
    $$[{"input":[2000],"expected_output":true},{"input":[1900],"expected_output":false},{"input":[2024],"expected_output":true},{"input":[2023],"expected_output":false}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Test a year divisible by 400, like 2000. What should it be, and what do you get?$$ from new_challenge
union all
select id, 2, $$The rule has three clauses; the code has two.$$ from new_challenge
union all
select id, 3, $$Add the exception: divisible by 400 makes it a leap year even though it is divisible by 100.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Free shipping threshold is off by a cent$$,
    $$javascript$$,
    $$logic_error$$,
    $$easy$$,
    $$qualifiesForFreeShipping$$,
    $$function qualifiesForFreeShipping(total) {
    return total > 50;
}$$,
    $$function qualifiesForFreeShipping(total) {
    return total >= 50;
}$$,
    $$qualifiesForFreeShipping(total) should return true when the order total is 50 or more — spending exactly 50 qualifies.$$,
    $$An order of exactly 50 returns false, so customers hitting the threshold are still charged.$$,
    $$'50 or more' includes 50 itself, which means >= rather than >. Boundary conditions are where requirements and code most often drift apart, and they rarely show up in casual testing because people try 49 and 51, not 50. When a spec says 'at least' or 'or more', the comparison is inclusive.$$,
    $$[{"input":[50],"expected_output":true},{"input":[49.99],"expected_output":false},{"input":[75],"expected_output":true}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try an order for exactly the threshold amount.$$ from new_challenge
union all
select id, 2, $$The comparison operator on the return line excludes one value it shouldn't.$$ from new_challenge
union all
select id, 3, $$"50 or more" includes 50, so use >= instead of >.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Grade boundaries return the wrong letter$$,
    $$python$$,
    $$logic_error$$,
    $$medium$$,
    $$grade$$,
    $$def grade(score):
    if score >= 60:
        return "D"
    elif score >= 70:
        return "C"
    elif score >= 80:
        return "B"
    elif score >= 90:
        return "A"
    return "F"$$,
    $$def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    return "F"$$,
    $$grade(score) should return "A" for 90+, "B" for 80-89, "C" for 70-79, "D" for 60-69, and "F" below 60.$$,
    $$A score of 95 returns "D" instead of "A".$$,
    $$In an if/elif chain the first matching branch wins, so the order of the conditions is part of the logic. Because 95 >= 60 is true, the chain stops at the very first branch and never reaches the check for 90. Overlapping ranges must be tested from the most restrictive to the least — highest threshold first.$$,
    $$[{"input":[95],"expected_output":"A"},{"input":[85],"expected_output":"B"},{"input":[72],"expected_output":"C"},{"input":[45],"expected_output":"F"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Walk through what happens for a score of 95, condition by condition.$$ from new_challenge
union all
select id, 2, $$Every branch after the first is unreachable for high scores. Why?$$ from new_challenge
union all
select id, 3, $$In an if/elif chain the first true branch wins — check the highest threshold first.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Digit sum never finishes$$,
    $$python$$,
    $$infinite_loop$$,
    $$medium$$,
    $$sum_digits$$,
    $$def sum_digits(n):
    total = 0
    while n > 0:
        total += n % 10
    return total$$,
    $$def sum_digits(n):
    total = 0
    while n > 0:
        total += n % 10
        n //= 10
    return total$$,
    $$sum_digits(n) should add up the digits of a number, so sum_digits(123) gives 6.$$,
    $$Calling sum_digits(123) hangs and never returns.$$,
    $$The loop reads the last digit with n % 10 but never removes it, so n keeps its original value and the condition n > 0 stays true forever. Digit-extraction loops need both halves: read the last digit, then drop it with integer division. Any while loop should make you ask what changes the condition.$$,
    $$[{"input":[123],"expected_output":6},{"input":[9],"expected_output":9},{"input":[4070],"expected_output":11}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The loop condition depends on n. Does anything in the body change n?$$ from new_challenge
union all
select id, 2, $$You read the last digit, but never remove it.$$ from new_challenge
union all
select id, 3, $$Add n //= 10 after the addition so the number shrinks each pass.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Reversing a string hangs the tab$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$medium$$,
    $$reverseString$$,
    $$function reverseString(text) {
    let out = "";
    let i = text.length - 1;
    while (i >= 0) {
        out += text[i];
    }
    return out;
}$$,
    $$function reverseString(text) {
    let out = "";
    let i = text.length - 1;
    while (i >= 0) {
        out += text[i];
        i--;
    }
    return out;
}$$,
    $$reverseString(text) should return the string backwards, so "abc" becomes "cba".$$,
    $$Calling reverseString("abc") freezes and never returns a value.$$,
    $$The index i is initialised and tested but never decremented, so the same character is appended forever and i >= 0 never becomes false. Manual index loops need three pieces — initialise, test, and step — and it's the step that's easiest to leave out when the loop body is doing something interesting.$$,
    $$[{"input":["abc"],"expected_output":"cba"},{"input":["a"],"expected_output":"a"},{"input":["debug"],"expected_output":"gubed"}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which variable does the loop condition depend on, and where is it changed?$$ from new_challenge
union all
select id, 2, $$The loop body appends a character but never moves the index.$$ from new_challenge
union all
select id, 3, $$Add i-- inside the loop so i eventually drops below 0.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Duplicate removal spins forever$$,
    $$javascript$$,
    $$infinite_loop$$,
    $$hard$$,
    $$dedupe$$,
    $$function dedupe(arr) {
    const out = [];
    let i = 0;
    while (i < arr.length) {
        if (!out.includes(arr[i])) {
            out.push(arr[i]);
        }
    }
    return out;
}$$,
    $$function dedupe(arr) {
    const out = [];
    let i = 0;
    while (i < arr.length) {
        if (!out.includes(arr[i])) {
            out.push(arr[i]);
        }
        i++;
    }
    return out;
}$$,
    $$dedupe(arr) should return the array with duplicates removed, keeping the first occurrence of each value.$$,
    $$Calling dedupe([1,2,2,3]) hangs — it never gets past the first element.$$,
    $$The index i is never incremented, so the loop re-tests position 0 forever — the first item gets added once, then the `includes` check keeps rejecting it while i stays put. A for...of loop would have advanced automatically; a manual while loop needs you to step the index yourself, and it's easy to forget when the body already has an if inside it.$$,
    $$[{"input":[[1,2,2,3]],"expected_output":[1,2,3]},{"input":[[1,1,1]],"expected_output":[1]},{"input":[[]],"expected_output":[]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Trace the first two iterations by hand. What is i each time?$$ from new_challenge
union all
select id, 2, $$The loop condition depends on i, and nothing in the body changes it.$$ from new_challenge
union all
select id, 3, $$Add i++ at the end of the loop body so it advances through the array.$$ from new_challenge;
