-- Generated by scripts/generate-seed-sql.mjs — do not hand-edit.
-- Change the source data in lib/seed-data/ and regenerate instead.
-- Run in the Supabase SQL Editor after migrations 0001, 0002 and 0003.
-- Second batch, part 3 of 5 (6 challenges). Run the parts in any order, each exactly once.
-- Every challenge here was executed and verified by
-- scripts/verify-challenges.mjs before being generated.

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Sorting numbers puts 10 before 9$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$sortNumbers$$,
    $$function sortNumbers(nums) {
    return nums.sort();
}$$,
    $$function sortNumbers(nums) {
    return nums.sort((a, b) => a - b);
}$$,
    $$sortNumbers(nums) should return the numbers sorted from smallest to largest.$$,
    $$sortNumbers([10, 9, 100, 1]) returns [1, 10, 100, 9] — 9 ends up last.$$,
    $$Array.sort() converts each element to a string and sorts lexicographically, so "10" sorts before "9" the same way "apple" sorts before "banana". Numeric sorting needs an explicit comparator, (a, b) => a - b. The default behaviour surprises almost everyone because it looks right for single-digit arrays.$$,
    $$[{"input":[[10,9,100,1]],"expected_output":[1,9,10,100]},{"input":[[3,1,2]],"expected_output":[1,2,3]},{"input":[[20,3]],"expected_output":[3,20]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Look closely at where 9 ends up relative to 10 and 100. Does that ordering look like anything else you know?$$ from new_challenge
union all
select id, 2, $$sort() with no arguments does not compare numbers the way you'd expect.$$ from new_challenge
union all
select id, 3, $$Pass a comparator: nums.sort((a, b) => a - b).$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Average always comes back as a whole number$$,
    $$python$$,
    $$type_error$$,
    $$easy$$,
    $$average$$,
    $$def average(nums):
    return sum(nums) // len(nums)$$,
    $$def average(nums):
    return sum(nums) / len(nums)$$,
    $$average(nums) should return the mean of a list of numbers, including any fractional part.$$,
    $$average([1, 2]) returns 1 instead of 1.5 — the decimal part disappears.$$,
    $$// is floor division: it discards the remainder and returns a whole number. Regular division with / keeps the fractional part. The two look almost identical when skimming code, and the bug only shows up for inputs that don't divide evenly — which is exactly why [2, 4] would have passed a casual test.$$,
    $$[{"input":[[1,2]],"expected_output":1.5},{"input":[[2,4]],"expected_output":3},{"input":[[1,2,4]],"expected_output":2.3333333333333335}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Try a list whose values don't divide evenly and compare with what you'd expect.$$ from new_challenge
union all
select id, 2, $$There are two division operators in Python. Which one is used here?$$ from new_challenge
union all
select id, 3, $$// floors the result. Use / to keep the fractional part.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Counting votes concatenates instead of adding$$,
    $$javascript$$,
    $$type_error$$,
    $$medium$$,
    $$countVotes$$,
    $$function countVotes(entries) {
    let total = 0;
    for (const entry of entries) {
        total += entry.votes;
    }
    return total;
}$$,
    $$function countVotes(entries) {
    let total = 0;
    for (const entry of entries) {
        total += Number(entry.votes);
    }
    return total;
}$$,
    $$countVotes(entries) should add up the votes field of every entry and return the numeric total.$$,
    $$countVotes with votes of "3" and "4" returns "034" instead of 7 — the digits are strung together.$$,
    $$The vote counts arrive as strings, and + means concatenation as soon as either operand is a string. Because the running total becomes a string on the very first addition, every later one concatenates too. Convert at the boundary where untrusted data enters your arithmetic, with Number() or parseInt(value, 10).$$,
    $$[{"input":[[{"votes":"3"},{"votes":"4"}]],"expected_output":7},{"input":[[{"votes":"10"},{"votes":"5"},{"votes":"1"}]],"expected_output":16},{"input":[[]],"expected_output":0}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$What type is entry.votes? Look at the quotes in the test cases.$$ from new_challenge
union all
select id, 2, $$In JavaScript + does two different jobs depending on the operand types.$$ from new_challenge
union all
select id, 3, $$Wrap the value in Number() before adding it to the total.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Every callback reports the same index$$,
    $$javascript$$,
    $$scope_error$$,
    $$hard$$,
    $$collectIndexes$$,
    $$function collectIndexes(n) {
    const out = [];
    const pending = [];
    for (var i = 0; i < n; i++) {
        pending.push(new Promise((resolve) => {
            setTimeout(() => { out.push(i); resolve(); }, 1);
        }));
    }
    return Promise.all(pending).then(() => out);
}$$,
    $$function collectIndexes(n) {
    const out = [];
    const pending = [];
    for (let i = 0; i < n; i++) {
        pending.push(new Promise((resolve) => {
            setTimeout(() => { out.push(i); resolve(); }, 1);
        }));
    }
    return Promise.all(pending).then(() => out);
}$$,
    $$collectIndexes(n) should schedule one callback per index and resolve to the list of indexes, so collectIndexes(3) gives [0, 1, 2].$$,
    $$collectIndexes(3) resolves to [3, 3, 3] — every callback reports the final value.$$,
    $$`var` is function-scoped, so all three callbacks close over the *same* i, and by the time the timeouts fire the loop has finished and i is 3. `let` is block-scoped and creates a fresh binding per iteration, so each callback captures its own value. This is the single most famous JavaScript closure bug, and it only appears when the callback runs later than the loop.$$,
    $$[{"input":[3],"expected_output":[0,1,2]},{"input":[1],"expected_output":[0]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$The callbacks run after the loop has already finished. What is i by then?$$ from new_challenge
union all
select id, 2, $$All the callbacks are sharing one variable rather than each getting their own.$$ from new_challenge
union all
select id, 3, $$var is function-scoped; let creates a new binding per iteration. Change var i to let i.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Shopping list remembers items between calls$$,
    $$python$$,
    $$scope_error$$,
    $$hard$$,
    $$make_baskets$$,
    $$def add_item(item, basket=[]):
    basket.append(item)
    return basket

def make_baskets(first, second):
    return [add_item(first), add_item(second)]$$,
    $$def add_item(item, basket=None):
    if basket is None:
        basket = []
    basket.append(item)
    return basket

def make_baskets(first, second):
    return [add_item(first), add_item(second)]$$,
    $$make_baskets(first, second) should start a separate basket for each item, so make_baskets("apple", "bread") gives [["apple"], ["bread"]].$$,
    $$make_baskets("apple", "bread") returns [["apple", "bread"], ["apple", "bread"]] — both baskets hold both items.$$,
    $$A default argument is evaluated once, when the function is defined, not on every call. So every call that omits `basket` shares one list that keeps growing for the lifetime of the program. The fix is the standard Python idiom: default to None and build a new list inside the function. Never use a mutable value as a default argument.$$,
    $$[{"input":["apple","bread"],"expected_output":[["apple"],["bread"]]},{"input":["milk","eggs"],"expected_output":[["milk"],["eggs"]]}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Both baskets contain the same two items. Are they even two different lists?$$ from new_challenge
union all
select id, 2, $$When exactly does Python evaluate the default value in a function signature — once, or on every call?$$ from new_challenge
union all
select id, 3, $$Default to None and create the list inside the function body.$$ from new_challenge;

with new_challenge as (
  insert into public.bug_challenges (
    title, language, bug_category, difficulty, function_name,
    broken_code, correct_code, problem_description, symptom_description,
    explanation, test_cases, status
  ) values (
    $$Discounted price is unreachable outside the branch$$,
    $$javascript$$,
    $$scope_error$$,
    $$medium$$,
    $$finalPrice$$,
    $$function finalPrice(price, isMember) {
    if (isMember) {
        const discounted = price * 0.9;
    } else {
        const discounted = price;
    }
    return discounted;
}$$,
    $$function finalPrice(price, isMember) {
    let discounted;
    if (isMember) {
        discounted = price * 0.9;
    } else {
        discounted = price;
    }
    return discounted;
}$$,
    $$finalPrice(price, isMember) should apply a 10% discount for members and return the price to pay.$$,
    $$Every call throws: ReferenceError: discounted is not defined.$$,
    $$`const` and `let` are block-scoped, so a variable declared inside an if or else block does not exist outside it — the two declarations here are separate variables, both gone by the time the return runs. Declare once in the enclosing scope and assign inside the branches.$$,
    $$[{"input":[100,true],"expected_output":90},{"input":[100,false],"expected_output":100},{"input":[50,true],"expected_output":45}]$$::jsonb,
    'published'
  )
  returning id
)
insert into public.hints (bug_challenge_id, hint_order, hint_text)
select id, 1, $$Which block is discounted declared in, and which block is it read from?$$ from new_challenge
union all
select id, 2, $$There are two separate declarations here, not one variable assigned twice.$$ from new_challenge
union all
select id, 3, $$Declare `let discounted;` before the if, then assign inside each branch.$$ from new_challenge;
